"""Pure language policy shared by the Worker user-settings routes."""

MODULATE_SUPPORTED_LANGUAGES = frozenset(
    {
        "en",
        "af",
        "sq",
        "ar",
        "az",
        "eu",
        "be",
        "bn",
        "bs",
        "bg",
        "ca",
        "zh",
        "hr",
        "cs",
        "da",
        "nl",
        "et",
        "fi",
        "fr",
        "gl",
        "de",
        "el",
        "gu",
        "he",
        "hi",
        "hu",
        "id",
        "it",
        "ja",
        "kn",
        "kk",
        "ko",
        "lv",
        "lt",
        "mk",
        "ms",
        "ml",
        "mr",
        "no",
        "fa",
        "pl",
        "pt",
        "pa",
        "ro",
        "ru",
        "sr",
        "sk",
        "sl",
        "es",
        "sw",
        "sv",
        "tl",
        "ta",
        "te",
        "th",
        "tr",
        "uk",
        "ur",
        "vi",
        "cy",
    }
)
ACCEPTED_LANGUAGE_BASES = MODULATE_SUPPORTED_LANGUAGES | {"multi", "mt"}
PRIMARY_LANGUAGE_OPTIONS = (
    ("en", "English"),
    ("en-US", "English (US)"),
    ("en-GB", "English (UK)"),
    ("en-AU", "English (Australia)"),
    ("en-NZ", "English (New Zealand)"),
    ("en-IN", "English (India)"),
    ("es", "Spanish"),
    ("es-419", "Spanish (Latin America)"),
    ("zh", "Chinese (Mandarin, Simplified)"),
    ("zh-CN", "Chinese (Mandarin, Simplified, CN)"),
    ("zh-Hans", "Chinese (Mandarin, Simplified, Hans)"),
    ("hi", "Hindi"),
    ("pt", "Portuguese"),
    ("pt-BR", "Portuguese (Brazil)"),
    ("pt-PT", "Portuguese (Portugal)"),
    ("ru", "Russian"),
    ("ja", "Japanese"),
    ("de", "German"),
    ("ar", "Arabic"),
    ("be", "Belarusian"),
    ("bn", "Bengali"),
    ("bs", "Bosnian"),
    ("bg", "Bulgarian"),
    ("ca", "Catalan"),
    ("zh-TW", "Chinese (Mandarin, Traditional)"),
    ("zh-Hant", "Chinese (Mandarin, Traditional, Hant)"),
    ("zh-HK", "Chinese (Cantonese, Traditional)"),
    ("hr", "Croatian"),
    ("cs", "Czech"),
    ("da", "Danish"),
    ("da-DK", "Danish (Denmark)"),
    ("nl", "Dutch"),
    ("et", "Estonian"),
    ("fi", "Finnish"),
    ("nl-BE", "Flemish"),
    ("fr", "French"),
    ("fr-CA", "French (Canada)"),
    ("de-CH", "German (Switzerland)"),
    ("el", "Greek"),
    ("he", "Hebrew"),
    ("hu", "Hungarian"),
    ("id", "Indonesian"),
    ("it", "Italian"),
    ("kn", "Kannada"),
    ("ko", "Korean"),
    ("ko-KR", "Korean (Korea)"),
    ("lv", "Latvian"),
    ("lt", "Lithuanian"),
    ("mk", "Macedonian"),
    ("ms", "Malay"),
    ("mr", "Marathi"),
    ("no", "Norwegian"),
    ("fa", "Persian"),
    ("pl", "Polish"),
    ("ro", "Romanian"),
    ("sr", "Serbian"),
    ("sk", "Slovak"),
    ("sl", "Slovenian"),
    ("sv", "Swedish"),
    ("sv-SE", "Swedish (Sweden)"),
    ("tl", "Tagalog"),
    ("ta", "Tamil"),
    ("te", "Telugu"),
    ("th", "Thai"),
    ("th-TH", "Thai (Thailand)"),
    ("tr", "Turkish"),
    ("uk", "Ukrainian"),
    ("ur", "Urdu"),
    ("vi", "Vietnamese"),
)

LANGUAGE_NAME_TO_BASE = {
    "afrikaans": "af",
    "albanian": "sq",
    "arabic": "ar",
    "azerbaijani": "az",
    "basque": "eu",
    "belarusian": "be",
    "bengali": "bn",
    "bosnian": "bs",
    "brazilian portuguese": "pt",
    "bulgarian": "bg",
    "cantonese": "zh",
    "catalan": "ca",
    "chinese": "zh",
    "chinese simplified": "zh",
    "chinese traditional": "zh",
    "croatian": "hr",
    "czech": "cs",
    "danish": "da",
    "dutch": "nl",
    "english": "en",
    "estonian": "et",
    "farsi": "fa",
    "filipino": "tl",
    "finnish": "fi",
    "flemish": "nl",
    "french": "fr",
    "galician": "gl",
    "german": "de",
    "greek": "el",
    "gujarati": "gu",
    "hebrew": "he",
    "hindi": "hi",
    "hungarian": "hu",
    "indonesian": "id",
    "italian": "it",
    "japanese": "ja",
    "kannada": "kn",
    "kazakh": "kk",
    "korean": "ko",
    "latvian": "lv",
    "lithuanian": "lt",
    "macedonian": "mk",
    "malay": "ms",
    "malayalam": "ml",
    "maltese": "mt",
    "mandarin": "zh",
    "marathi": "mr",
    "norwegian": "no",
    "persian": "fa",
    "polish": "pl",
    "portuguese": "pt",
    "punjabi": "pa",
    "romanian": "ro",
    "russian": "ru",
    "serbian": "sr",
    "simplified chinese": "zh",
    "slovak": "sk",
    "slovenian": "sl",
    "spanish": "es",
    "swahili": "sw",
    "swedish": "sv",
    "tagalog": "tl",
    "tamil": "ta",
    "telugu": "te",
    "thai": "th",
    "turkish": "tr",
    "ukrainian": "uk",
    "urdu": "ur",
    "vietnamese": "vi",
    "welsh": "cy",
}
