"""Prepare canonical privacy deletion in one fenced D1 transaction.

Only authenticated route owners may choose uid/IDs. This function returns durable
cleanup inventory, never a success acknowledgement: the existing Jobs provider
owner and finalizer must still establish erasure before a caller acknowledges.
"""

from datetime import datetime, timezone
import secrets

from memory_apply_item import read_item
from memory_apply_intake import (
    MODEL_COLUMNS,
    _insert_rows,
    _stored_item,
    append_journal_records,
    control_statement,
    encoded,
    read_memory_control,
)
from memory_privacy_plan import build_privacy_result
from memory_privacy_receipts import privacy_receipt_id
from memory_review_store import CanonicalReviewResolution

LINEAGE_SQL = '''WITH RECURSIVE lineage(id) AS (
  SELECT value FROM json_each(?)
  UNION
  SELECT CASE WHEN e.id = l.id THEN e.parent_id ELSE e.id END
  FROM cf_memory_lineage_edges e JOIN lineage l ON e.id = l.id OR e.parent_id = l.id
  WHERE e.uid = ?
) SELECT id FROM cf_memories WHERE uid = ? AND id IN (SELECT id FROM lineage) ORDER BY id LIMIT 101'''
EXPECTED_FIELDS = (
    'id',
    'item_revision',
    'version',
    'canonical_metadata_json',
    'capture_device_ids_json',
    'primary_capture_device',
)
SCRUB_COLUMNS = {
    'category': 'interesting',
    'tags_json': '[]',
    'headline': None,
    'subject_attribution': 'unknown',
    'object_entity_ids_json': '[]',
    'qualifiers_json': '{}',
    'capture_confidence': None,
    'veracity': None,
    'uncertainty_reasons_json': '[]',
    'durability': None,
    'conversation_id': None,
    'scoring': None,
    'app_id': None,
    'data_protection_source_revision': None,
}


def gate_statement(db, uid, token, now, *, resume=False):
    selection = (
        "SELECT uid, 'explicit_memory_deletion', token, 'running', ?, NULL "
        'FROM cf_memory_privacy_deletions WHERE uid = ? AND token = ? '
        if resume
        else "VALUES (?, 'explicit_memory_deletion', ?, 'running', ?, NULL) "
    )
    statement = db.prepare(
        'INSERT INTO cf_destructive_operation_gates(uid, kind, token, state, started_at, finished_at) '
        + selection
        + 'ON CONFLICT(uid) DO UPDATE SET '
        'kind = excluded.kind, token = excluded.token, state = excluded.state, '
        'started_at = excluded.started_at, finished_at = NULL'
    )
    return statement.bind(now, uid, token) if resume else statement.bind(uid, token, now)


async def lineage_ids(db, uid, requested_ids):
    result = await db.prepare(LINEAGE_SQL).bind(encoded(requested_ids), uid, uid).all()
    found = [row['id'] for row in result['results']]
    if not set(requested_ids).issubset(found):
        raise ValueError('memory_privacy_target_not_found')
    if len(found) > 100:
        raise ValueError('memory_privacy_lineage_too_large')
    return found


async def prepare_privacy_deletion(
    env, uid, requested_ids, now, *, expand_lineages=True, review_resolution: CanonicalReviewResolution | None = None
):
    if (
        not isinstance(uid, str)
        or not uid
        or not requested_ids
        or len(requested_ids) > 100
        or len(set(requested_ids)) != len(requested_ids)
        or any(not isinstance(value, str) or not value or len(value) > 256 for value in requested_ids)
    ):
        raise ValueError('invalid privacy deletion identities')
    if review_resolution is not None and requested_ids != [review_resolution.review['fact_id']]:
        raise ValueError('invalid review privacy target')
    requested_ids = sorted(requested_ids)
    requested_json = encoded(requested_ids)
    db = env.APP_DB
    pending = await db.prepare('SELECT * FROM cf_memory_privacy_deletions WHERE uid = ?').bind(uid).first()
    if pending is not None:
        if pending['requested_ids_json'] != requested_json:
            raise ValueError('memory_privacy_cleanup_pending')
        # The token was generated by this owner and read from durable inventory.
        # Reacquire only through the same legal-hold/competing-owner authority.
        resumed = await gate_statement(db, uid, pending['token'], now, resume=True).run()
        if resumed['meta']['changes'] != 1:
            raise ValueError('memory_privacy_inventory_changed')
        return pending
    prior, control = await read_memory_control(env, uid)
    ids = await lineage_ids(db, uid, requested_ids) if expand_lineages else requested_ids
    items, expected, stored = [], [], []
    for memory_id in ids:
        row = await db.prepare('SELECT * FROM cf_memories WHERE uid = ? AND id = ?').bind(uid, memory_id).first()
        if row is None:
            raise ValueError('memory_privacy_targets_changed')
        item = read_item(row)
        if item.account_generation != control.account_generation:
            raise ValueError('memory_apply_generation_changed')
        if review_resolution is not None and memory_id == review_resolution.review['fact_id']:
            review_resolution.validate(item)
        items.append(item)
        expected.append({key: row[key] for key in EXPECTED_FIELDS})
        # Do not retain a second copy of plaintext while building scrubbed rows.
        stored.append({'uid': uid, 'id': memory_id, 'privacy_receipt_id': privacy_receipt_id(env, uid, memory_id)})
    token = secrets.token_hex(32)
    result = build_privacy_result(
        control,
        items,
        epoch_nonce=token,
        now=datetime.fromtimestamp(now, timezone.utc),
        reason='canonical_review_' + review_resolution.decision if review_resolution else 'explicit_memory_deletion',
    )
    items.clear()
    for index, tombstone in enumerate(result.memory_items):
        stored[index] = _stored_item(stored[index], tombstone)
        stored[index].update(SCRUB_COLUMNS, deleted_at=now)
    targets = [
        {'id': row['id'], 'item_revision': row['item_revision'], 'receipt_id': row['privacy_receipt_id']}
        for row in stored
    ]
    inventory = {
        'uid': uid,
        'token': token,
        'requested_ids_json': requested_json,
        'targets_json': encoded(targets),
        'created_at': now,
        'last_attempt_at': 0,
        'expand_lineages': int(expand_lineages),
    }
    statements = [
        gate_statement(db, uid, token, now),
        db.prepare(
            'INSERT INTO cf_memory_privacy_apply_guard(uid, token, expected_control_json, account_generation, '
            'requested_ids_json, expected_items_json, expand_lineages) VALUES (?, ?, ?, ?, ?, ?, ?)'
        ).bind(uid, token, prior, control.account_generation, requested_json, encoded(expected), int(expand_lineages)),
        *_insert_rows(db, 'cf_memory_privacy_deletions', [inventory]),
    ]
    if review_resolution is not None:
        statements.append(review_resolution.admission(db, uid))
    columns = sorted(
        (
            set(MODEL_COLUMNS.values())
            | set(SCRUB_COLUMNS)
            | {
                'canonical_metadata_json',
                'deleted_at',
                'privacy_receipt_id',
            }
        )
        - {'uid', 'id'}
    )
    for row in stored:
        statements.append(
            db.prepare(
                'UPDATE cf_memories SET '
                + ', '.join(column + ' = ?' for column in columns)
                + ' WHERE uid = ? AND id = ?'
            ).bind(*(row[column] for column in columns), uid, row['id'])
        )
    records = {table: [] for table in ('cf_memory_operations', 'cf_memory_commits', 'cf_memory_outbox')}
    # The privacy epoch cannot retain a content-derived pre-delete head as its
    # parent. This is the original privacy transaction's independent parent.
    privacy_parent = control.model_copy(update={'head_commit_id': result.control_state.head_commit_id})
    append_journal_records(records, uid, result, privacy_parent, now)
    for table, values in records.items():
        statements.extend(_insert_rows(db, table, values))
    statements.append(control_statement(db, uid, result.control_state))
    if review_resolution is not None:
        statements.extend(review_resolution.resolution_statements(db, uid, result.control_state.head_commit_id, now))
    # Seal last: every later update, including trigger updates, is denied by the
    # receipt fence. All row, journal and projection mutations precede sealing.
    statements.extend(
        _insert_rows(
            db,
            'cf_memory_privacy_receipts',
            [
                {'uid': uid, 'receipt_id': target['receipt_id'], 'created_at': now, 'expires_at': now + 2592000}
                for target in targets
            ],
        )
    )
    statements.append(db.prepare('DELETE FROM cf_memory_privacy_apply_guard WHERE uid = ?').bind(uid))
    await db.batch(statements)
    return inventory
