import { describe, expect, it } from "vitest";
import {
  decryptLegacyDataProtection,
  encryptLegacyDataProtection,
  LEGACY_DATA_PROTECTION_CONTRACT,
  parseLegacyCiphertext,
  LegacyDataProtectionError,
} from "../workers/shared/legacy-data-protection";

const SECRET = "0123456789abcdef0123456789abcdef";
const UID = "fixture-user";
// Generated by backend/utils/encryption.py with the same secret, uid, and a
// fixed nonce of 00..0b. This proves the HKDF/AES-GCM wire contract across
// Python and Workers without making production migration behavior active.
const PYTHON_FIXTURE =
  "AAECAwQFBgcICQoLwGoXta/tU/qwYOcqZLnszT3deJg6NKkKdWJAa39X0BM=";

describe("legacy data-protection Web Crypto contract", () => {
  it("decrypts the Python HKDF-SHA256/AES-256-GCM fixture", async () => {
    expect(parseLegacyCiphertext(PYTHON_FIXTURE)).toBe(PYTHON_FIXTURE);
    await expect(
      decryptLegacyDataProtection(SECRET, UID, PYTHON_FIXTURE),
    ).resolves.toBe("hello cloudflare");
  });

  it("emits standard Base64 and decrypts its own randomized envelope", async () => {
    const encrypted = await encryptLegacyDataProtection(
      SECRET,
      UID,
      "cross-runtime text ✓",
    );
    expect(encrypted).toMatch(/^[A-Za-z0-9+/]+=*$/);
    expect(parseLegacyCiphertext(encrypted)).toBe(encrypted);
    await expect(
      decryptLegacyDataProtection(SECRET, UID, encrypted),
    ).resolves.toBe("cross-runtime text ✓");
  });

  it("rejects URL-safe/non-canonical, truncated, and tampered values", async () => {
    const urlSafe = PYTHON_FIXTURE.replaceAll("/", "_").replaceAll("+", "-");
    expect(() => parseLegacyCiphertext(urlSafe)).toThrow(LegacyDataProtectionError);
    expect(() => parseLegacyCiphertext(PYTHON_FIXTURE.slice(0, -1))).toThrow(
      LegacyDataProtectionError,
    );
    expect(() => parseLegacyCiphertext("AA==")).toThrow(LegacyDataProtectionError);

    const tampered = `${PYTHON_FIXTURE.slice(0, -2)}AA`;
    await expect(
      decryptLegacyDataProtection(SECRET, UID, tampered),
    ).rejects.toThrow("authentication failed");
    await expect(
      decryptLegacyDataProtection("wrong-secret-that-is-long-enough-32", UID, PYTHON_FIXTURE),
    ).rejects.toThrow("authentication failed");
  });

  it("treats only the legacy empty optional value as absent", async () => {
    expect(parseLegacyCiphertext("")).toBeNull();
    await expect(decryptLegacyDataProtection(SECRET, UID, "")).resolves.toBe("");
    await expect(encryptLegacyDataProtection(SECRET, UID, "")).resolves.toBe("");
    expect(LEGACY_DATA_PROTECTION_CONTRACT).toMatchObject({
      info: "user-data-encryption",
      nonceBytes: 12,
      tagBytes: 16,
      secretMinBytes: 32,
    });
  });

  it("fails closed for invalid secret, uid, and plaintext inputs", async () => {
    await expect(
      encryptLegacyDataProtection("too-short", UID, "secret"),
    ).rejects.toThrow(LegacyDataProtectionError);
    await expect(
      decryptLegacyDataProtection(SECRET, "", PYTHON_FIXTURE),
    ).rejects.toThrow(LegacyDataProtectionError);
    await expect(
      encryptLegacyDataProtection(SECRET, UID, 42 as never),
    ).rejects.toThrow(LegacyDataProtectionError);
  });
});
