#!/usr/bin/env bash
# LIFECYCLE: permanent
# Run Compose with the reviewed env file as the only authority for deployment
# keys. Docker Compose otherwise gives an ambient shell variable precedence
# over the same key in --env-file.

set -euo pipefail

ENV_FILE="${1:?environment file path is required}"
COMPOSE_FILE="${2:?Compose file path is required}"
shift 2

[[ -f "$ENV_FILE" ]] || {
  echo "error: Compose environment file not found: $ENV_FILE" >&2
  exit 1
}
[[ -f "$COMPOSE_FILE" ]] || {
  echo "error: Compose file not found: $COMPOSE_FILE" >&2
  exit 1
}

clean_env=(env)
# Compose itself also consumes ambient control variables before it evaluates
# the reviewed file.  Keep project/file/profile selection owned by this
# invocation; otherwise a stale shell export can silently select a different
# project, profile, or interpolation source.  DOCKER_HOST/DOCKER_CONTEXT are
# intentionally preserved: they select the operator's explicit Docker
# authority, not the Compose application configuration.
for key in \
  COMPOSE_ANSI \
  COMPOSE_CONFIG \
  COMPOSE_CONVERT_WINDOWS_PATHS \
  COMPOSE_ENV_FILES \
  COMPOSE_FILE \
  COMPOSE_IGNORE_ORPHANS \
  COMPOSE_PARALLEL_LIMIT \
  COMPOSE_PATH_SEPARATOR \
  COMPOSE_PROFILES \
  COMPOSE_PROGRESS \
  COMPOSE_PROJECT_NAME \
  COMPOSE_REMOVE_ORPHANS; do
  clean_env+=(-u "$key")
done
dotenv_keys="$(python3 -c 'import re,sys; print("\n".join(line.split("=",1)[0].strip() for line in open(sys.argv[1],encoding="utf-8") if "=" in line and re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", line.split("=",1)[0].strip())))' "$ENV_FILE")" || {
  echo "error: could not read deployment keys from $ENV_FILE" >&2
  exit 1
}
if [[ -n "$dotenv_keys" ]]; then
  while IFS= read -r key; do
    clean_env+=(-u "$key")
  done <<<"$dotenv_keys"
fi

# These values are generated by the acceptance runner after source/config
# attribution. The CUTOVER values control only the disposable local overlay.
# Re-apply them after deployment keys are removed even if a reviewed env file
# happens to declare a key with the same name.
[[ -z "${OMI_SOURCE_GIT_COMMIT+x}" ]] || clean_env+=("OMI_SOURCE_GIT_COMMIT=$OMI_SOURCE_GIT_COMMIT")
[[ -z "${OMI_SOURCE_GIT_TREE+x}" ]] || clean_env+=("OMI_SOURCE_GIT_TREE=$OMI_SOURCE_GIT_TREE")
[[ -z "${OMI_RUNTIME_CONFIG_SHA256+x}" ]] || clean_env+=("OMI_RUNTIME_CONFIG_SHA256=$OMI_RUNTIME_CONFIG_SHA256")
[[ -z "${CUTOVER_HTTPS_PORT+x}" ]] || clean_env+=("CUTOVER_HTTPS_PORT=$CUTOVER_HTTPS_PORT")
[[ -z "${CUTOVER_TLS_CERT_PATH+x}" ]] || clean_env+=("CUTOVER_TLS_CERT_PATH=$CUTOVER_TLS_CERT_PATH")
[[ -z "${CUTOVER_TLS_KEY_PATH+x}" ]] || clean_env+=("CUTOVER_TLS_KEY_PATH=$CUTOVER_TLS_KEY_PATH")

exec "${clean_env[@]}" docker compose --env-file "$ENV_FILE" --file "$COMPOSE_FILE" "$@"
