#!/usr/bin/env python3
# LIFECYCLE: permanent
"""Export authoritative product rows for a vector projection rebuild.

The vector index is deliberately not consulted by this command.  The only
runtime dependency is the read-only Firestore-compatible facade exposed by
``database._client``.  In a self-host deployment that facade is backed by
PostgreSQL (``FIRESTORE_PG_DSN``); in the managed deployment it is backed by
Firestore.  The same source shape therefore drives a Pinecone-to-Qdrant
rebuild without carrying a Pinecone export forward as authority.

Each namespace is emitted as strict JSONL with exactly ``id``, ``content`` and
``metadata`` fields.  ``manifest.json`` binds each file's bytes, count and
source collection.  No vector values are emitted: embeddings are generated by
the explicitly configured migration runtime after this source export is
verified.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from collections.abc import Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass
from datetime import date, datetime
from enum import Enum
from pathlib import Path
from typing import Any, Protocol

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

NAMESPACE_ORDER = (
    'ns1',
    'ns2',
    'workstream-association-v1',
    'ns_x',
    'ns3',
    'ns4',
    'ns_tchunks',
)
EXPORT_FORMAT = 'omi-authoritative-vector-export-v1'
MANIFEST_FORMAT = 'omi-authoritative-vector-export-manifest-v1'
_RECORD_KEYS = frozenset({'id', 'content', 'metadata'})


class ExportError(RuntimeError):
    """An operator input or authoritative-source contract failed."""


@dataclass(frozen=True)
class SourceDocument:
    id: str
    data: Mapping[str, Any]


class ReadOnlyAuthority(Protocol):
    """Minimal source contract; implementations must not expose writes."""

    source_kind: str

    def list_uids(self) -> Iterable[str]: ...

    def iter_user_documents(self, uid: str, collection: str) -> Iterable[SourceDocument]: ...


class FirestoreFacadeAuthority:
    """Read-only adapter over the repository's Firestore/PG compatibility seam."""

    def __init__(self, client: Any | None = None) -> None:
        if client is None:
            from database import _client as database_client

            client = database_client.db
        self._client = client
        self.source_kind = 'firestore_pg_facade' if os.getenv('FIRESTORE_PG_DSN', '').strip() else 'firestore_facade'

    def list_uids(self) -> Iterable[str]:
        for snapshot in self._client.collection('users').stream():
            uid = str(getattr(snapshot, 'id', '') or '').strip()
            if not uid:
                raise ExportError('authoritative users collection contains a blank document id')
            yield uid

    def iter_user_documents(self, uid: str, collection: str) -> Iterable[SourceDocument]:
        if not uid.strip():
            raise ExportError('uid must be non-empty')
        if not collection or '/' in collection:
            raise ExportError(f'unsupported collection {collection!r}')
        ref = self._client.collection('users').document(uid).collection(collection)
        for snapshot in ref.stream():
            document_id = str(getattr(snapshot, 'id', '') or '').strip()
            if not document_id:
                raise ExportError(f'{uid}/{collection} contains a blank document id')
            raw = snapshot.to_dict()
            if not isinstance(raw, Mapping):
                raise ExportError(f'{uid}/{collection}/{document_id} is not a JSON object')
            yield SourceDocument(id=document_id, data=dict(raw))


@dataclass(frozen=True)
class NamespaceSpec:
    collection: str | tuple[str, ...]


NAMESPACE_SPECS: dict[str, NamespaceSpec] = {
    'ns1': NamespaceSpec('conversations'),
    'ns2': NamespaceSpec('memory_items'),
    'workstream-association-v1': NamespaceSpec('workstreams'),
    'ns_x': NamespaceSpec('x_posts'),
    'ns3': NamespaceSpec('screen_activity'),
    'ns4': NamespaceSpec('action_items'),
    'ns_tchunks': NamespaceSpec('conversations'),
}


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    owner = parser.add_mutually_exclusive_group(required=True)
    owner.add_argument('--uid', action='append', dest='uids', help='Export one UID; may be repeated.')
    owner.add_argument('--all-users', action='store_true', help='Enumerate the authoritative users collection.')
    parser.add_argument(
        '--namespace',
        action='append',
        choices=NAMESPACE_ORDER,
        help='Export only this namespace; may be repeated (default: all seven).',
    )
    parser.add_argument('--output-dir', type=Path, required=True, help='New directory for namespace JSONL files.')
    parser.add_argument(
        '--sidecar',
        type=Path,
        help='Manifest path (default: OUTPUT_DIR/manifest.json). The file must not already exist.',
    )
    parser.add_argument(
        '--allow-empty',
        action='store_true',
        help='Explicitly acknowledge a namespace with no authoritative rows; default is fail-closed.',
    )
    return parser.parse_args(argv)


def export_authoritative_vectors(
    authority: ReadOnlyAuthority,
    *,
    uids: Iterable[str] | None,
    all_users: bool,
    namespaces: Iterable[str] | None,
    output_dir: Path,
    sidecar: Path | None = None,
    allow_empty: bool = False,
) -> dict[str, Any]:
    """Export selected source rows and return the same data written to sidecar."""

    selected_uids = _resolve_uids(authority, uids=uids, all_users=all_users)
    selected_namespaces = _resolve_namespaces(namespaces)
    if output_dir.exists():
        if not output_dir.is_dir():
            raise ExportError(f'output path exists and is not a directory: {output_dir}')
        if any(output_dir.iterdir()):
            raise ExportError(f'output directory must be new or empty: {output_dir}')
    else:
        output_dir.mkdir(parents=True, exist_ok=False)
    manifest_path = sidecar or output_dir / 'manifest.json'
    if manifest_path.exists():
        raise ExportError(f'manifest already exists: {manifest_path}')
    if manifest_path.parent != output_dir:
        manifest_path.parent.mkdir(parents=True, exist_ok=True)

    files: list[dict[str, Any]] = []
    for namespace in selected_namespaces:
        records = _records_for_namespace(authority, namespace, selected_uids)
        if not records and not allow_empty:
            raise ExportError(
                f'authoritative export for namespace {namespace!r} is empty; '
                'pass --allow-empty only after confirming that the namespace is intentionally unused'
            )
        filename = f'{_safe_filename(namespace)}.jsonl'
        output_path = output_dir / filename
        record_count, sha256 = _write_jsonl(output_path, records)
        files.append(
            {
                'namespace': namespace,
                'path': filename,
                'source_collection': NAMESPACE_SPECS[namespace].collection,
                'record_count': record_count,
                'sha256': sha256,
            }
        )

    manifest: dict[str, Any] = {
        'format': MANIFEST_FORMAT,
        'export_format': EXPORT_FORMAT,
        'source_kind': authority.source_kind,
        'uid_count': len(selected_uids),
        'namespace_count': len(selected_namespaces),
        'empty_export_acknowledged': bool(allow_empty),
        'namespaces': list(selected_namespaces),
        'files': files,
    }
    _write_manifest(manifest_path, manifest)
    return manifest


def _resolve_uids(authority: ReadOnlyAuthority, *, uids: Iterable[str] | None, all_users: bool) -> tuple[str, ...]:
    if all_users:
        raw_uids = list(authority.list_uids())
    else:
        raw_uids = list(uids or ())
    normalized = [str(uid).strip() for uid in raw_uids]
    if any(not uid for uid in normalized):
        raise ExportError('UID values must be non-empty')
    unique = sorted(set(normalized))
    if len(unique) != len(normalized):
        raise ExportError('duplicate UID values are not allowed')
    if not unique:
        raise ExportError('at least one authoritative UID is required')
    return tuple(unique)


def _resolve_namespaces(namespaces: Iterable[str] | None) -> tuple[str, ...]:
    if namespaces is None:
        return NAMESPACE_ORDER
    raw_namespaces = tuple(str(namespace).strip() for namespace in namespaces)
    selected = tuple(dict.fromkeys(raw_namespaces))
    if not selected or any(namespace not in NAMESPACE_SPECS for namespace in selected):
        raise ExportError(f'namespace must be a duplicate-free subset of {NAMESPACE_ORDER!r}')
    if len(selected) != len(raw_namespaces):
        raise ExportError('duplicate namespace values are not allowed')
    return tuple(namespace for namespace in NAMESPACE_ORDER if namespace in selected)


def _records_for_namespace(
    authority: ReadOnlyAuthority,
    namespace: str,
    uids: Sequence[str],
) -> tuple[dict[str, Any], ...]:
    records: list[dict[str, Any]] = []
    for uid in uids:
        if namespace == 'ns_tchunks':
            records.extend(_transcript_chunk_records(authority, uid))
            continue
        spec = NAMESPACE_SPECS[namespace]
        assert isinstance(spec.collection, str)
        for document in authority.iter_user_documents(uid, spec.collection):
            record = _record_from_document(namespace, uid, document)
            if record is not None:
                records.append(record)
    records.sort(key=lambda record: (str(record['metadata'].get('uid', '')), str(record['id'])))
    return tuple(records)


def _record_from_document(namespace: str, uid: str, document: SourceDocument) -> dict[str, Any] | None:
    data = dict(document.data)
    if data.get('uid') not in (None, uid):
        raise ExportError(f'{uid}/{NAMESPACE_SPECS[namespace].collection}/{document.id} has a mismatched uid')
    if namespace == 'ns1':
        if _is_locked(data) or data.get('discarded') is True:
            return None
        structured = data.get('structured')
        structured_map = structured if isinstance(structured, Mapping) else {}
        title = _text(structured_map.get('title'))
        overview = _text(structured_map.get('overview'))
        content = overview or title
        if not content:
            return None
        metadata = {
            'uid': uid,
            'memory_id': document.id,
            'conversation_id': document.id,
            'created_at': _timestamp(data.get('created_at')),
        }
        return _record(f'{uid}-{document.id}', content, metadata)

    if namespace == 'ns2':
        if data.get('status') not in (None, 'active'):
            return None
        content = _text(data.get('content'))
        if not content:
            return None
        memory_id = _text(data.get('memory_id')) or document.id
        metadata = {
            'uid': uid,
            'memory_id': memory_id,
            'category': _text(data.get('category')) or _text(data.get('predicate')),
            'status': _text(data.get('status')) or 'active',
            'tier': _enum_value(data.get('tier')),
            'subject_entity_id': _text(data.get('subject_entity_id')),
        }
        return _record(f'{uid}-{memory_id}', content, metadata)

    if namespace == 'workstream-association-v1':
        if data.get('status') not in (None, 'open'):
            return None
        workstream_id = _text(data.get('workstream_id')) or document.id
        objective = _text(data.get('objective'))
        state = _text(data.get('current_state_summary'))
        content = '\n'.join(
            part
            for part in (f'Objective: {objective}' if objective else '', f'Current state: {state}' if state else '')
            if part
        )
        if not content:
            return None
        generation = _integer(data.get('account_generation'), default=0)
        metadata = {
            'uid': uid,
            'workstream_id': workstream_id,
            'status': 'open',
            'account_generation': generation,
            'schema_version': 1,
        }
        return _record(f'{uid}:workstream:{generation}:{workstream_id}', content, metadata)

    if namespace == 'ns_x':
        content = _text(data.get('text')) or _text(data.get('content'))
        if not content:
            return None
        post_id = _text(data.get('id')) or document.id
        metadata = {
            'uid': uid,
            'post_id': post_id,
            'kind': _text(data.get('kind')) or 'tweet',
            'created_at': _timestamp(data.get('created_at')),
        }
        return _record(f'{uid}-x-{post_id}', content, metadata)

    if namespace == 'ns3':
        content = _text(data.get('ocrText')) or _text(data.get('ocr_text'))
        if not content:
            return None
        screenshot_id = _text(data.get('storageId')) or _text(data.get('storage_id')) or document.id
        metadata = {
            'uid': uid,
            'screenshot_id': screenshot_id,
            'timestamp': _timestamp(data.get('timestamp')),
            'appName': _text(data.get('appName')),
        }
        return _record(f'{uid}-sa-{screenshot_id}', content, metadata)

    if namespace == 'ns4':
        if data.get('deleted') is True or data.get('status') in ('cancelled', 'superseded'):
            return None
        content = _text(data.get('description'))
        if not content:
            return None
        action_item_id = _text(data.get('id')) or document.id
        metadata = {
            'uid': uid,
            'action_item_id': action_item_id,
            'status': _text(data.get('status')) or ('completed' if data.get('completed') is True else 'active'),
            'created_at': _timestamp(data.get('created_at')),
        }
        return _record(f'{uid}-ai-{action_item_id}', content, metadata)

    raise ExportError(f'unsupported namespace {namespace!r}')


def _transcript_chunk_records(authority: ReadOnlyAuthority, uid: str) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for document in authority.iter_user_documents(uid, 'conversations'):
        data = dict(document.data)
        if _is_locked(data) or data.get('discarded') is True:
            continue
        data = _decode_conversation_for_export(uid, data)
        segments = data.get('transcript_segments')
        if not isinstance(segments, list):
            # Encrypted/compressed transcripts are intentionally not guessed at
            # this generic authority boundary. The production conversation
            # reader must expose decoded segments before this namespace is
            # exported; silently indexing an empty transcript is unsafe.
            if segments:
                raise ExportError(
                    f'{uid}/conversations/{document.id} transcript_segments are not decoded; '
                    'run the export with the repository conversation facade'
                )
            continue
        started_at = data.get('started_at') or data.get('created_at')
        chunks = _build_chunks(segments, started_at)
        for chunk in chunks:
            index = int(chunk['chunk_index'])
            records.append(
                _record(
                    f'{uid}-{document.id}-c{index}',
                    str(chunk['text']),
                    {
                        'uid': uid,
                        'conversation_id': document.id,
                        'chunk_index': index,
                        'created_at': int(chunk['created_at']),
                    },
                )
            )
    return records


def _decode_conversation_for_export(uid: str, data: dict[str, Any]) -> dict[str, Any]:
    """Decode the repository's compressed/encrypted transcript at the source boundary."""
    raw_segments = data.get('transcript_segments')
    if not raw_segments or isinstance(raw_segments, list):
        return data
    try:
        from database.conversations import _prepare_conversation_for_read

        decoded = _prepare_conversation_for_read(data, uid)
    except Exception as error:
        raise ExportError(f'conversation transcript is not decoded for uid {uid}') from error
    if not isinstance(decoded, Mapping):
        raise ExportError(f'conversation transcript decode returned an invalid document for uid {uid}')
    return dict(decoded)


def _build_chunks(segments: list[Any], started_at: Any) -> list[dict[str, Any]]:
    """Small dependency-free equivalent of the production chunking contract."""
    lines: list[str] = []
    for segment in segments:
        if not isinstance(segment, Mapping):
            raise ExportError('transcript segment must be an object')
        text = _text(segment.get('text'))
        if not text:
            continue
        label = (
            'User'
            if segment.get('is_user')
            else (f"Speaker {segment.get('speaker_id')}" if segment.get('speaker_id') is not None else 'Speaker')
        )
        lines.append(f'{label}: {text}')
    if not lines:
        return []
    date_header = ''
    created_at = _timestamp(started_at)
    if isinstance(started_at, datetime):
        date_header = f'[Conversation on {started_at.strftime("%d %b %Y, %H:%M")}]\n'
    chunks: list[dict[str, Any]] = []
    position = 0
    index = 0
    while position < len(lines):
        chunks.append(
            {
                'text': date_header + '\n'.join(lines[position : position + 8]),
                'created_at': created_at,
                'chunk_index': index,
            }
        )
        if position + 8 >= len(lines):
            break
        position += 6
        index += 1
    return chunks


def _record(record_id: str, content: str, metadata: Mapping[str, Any]) -> dict[str, Any]:
    if not record_id.strip() or not content.strip():
        raise ExportError('authoritative vector record id/content must be non-empty')
    normalized = {key: value for key, value in metadata.items() if value is not None and value != ''}
    record = {'id': record_id, 'content': content, 'metadata': _json_safe(normalized)}
    if set(record) != _RECORD_KEYS:
        raise ExportError('internal exporter produced a non-strict record')
    return record


def _write_jsonl(path: Path, records: Iterable[Mapping[str, Any]]) -> tuple[int, str]:
    digest = hashlib.sha256()
    count = 0
    try:
        with path.open('xb') as handle:
            for value in records:
                if set(value) != _RECORD_KEYS:
                    raise ExportError(f'internal exporter produced invalid JSONL record for {path.name}')
                line = (
                    json.dumps(
                        value, ensure_ascii=False, sort_keys=True, separators=(',', ':'), allow_nan=False
                    ).encode('utf-8')
                    + b'\n'
                )
                handle.write(line)
                digest.update(line)
                count += 1
    except FileExistsError as error:
        raise ExportError(f'output file already exists: {path}') from error
    except BaseException:
        path.unlink(missing_ok=True)
        raise
    return count, digest.hexdigest()


def _write_manifest(path: Path, manifest: Mapping[str, Any]) -> None:
    payload = json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2, allow_nan=False) + '\n'
    try:
        with path.open('x', encoding='utf-8') as handle:
            handle.write(payload)
    except FileExistsError as error:
        raise ExportError(f'manifest already exists: {path}') from error


def _safe_filename(namespace: str) -> str:
    return namespace.replace('-', '_')


def _text(value: Any) -> str:
    return value.strip() if isinstance(value, str) else ''


def _enum_value(value: Any) -> Any:
    return value.value if isinstance(value, Enum) else value


def _integer(value: Any, *, default: int) -> int:
    if value is None:
        return default
    if isinstance(value, bool):
        raise ExportError('boolean cannot be used as an integer authority field')
    try:
        return int(value)
    except (TypeError, ValueError) as error:
        raise ExportError(f'invalid integer authority field: {value!r}') from error


def _timestamp(value: Any) -> int:
    if value is None:
        return 0
    if isinstance(value, bool):
        raise ExportError('boolean cannot be used as a timestamp authority field')
    if isinstance(value, datetime):
        return int(value.timestamp())
    if isinstance(value, date):
        return int(datetime(value.year, value.month, value.day).timestamp())
    try:
        return int(value)
    except (TypeError, ValueError) as error:
        raise ExportError(f'invalid timestamp authority field: {value!r}') from error


def _is_locked(data: Mapping[str, Any]) -> bool:
    return data.get('is_locked') is True or data.get('data_protection_level') == 'enhanced'


def _json_safe(value: Any) -> Any:
    value = _enum_value(value)
    if value is None or isinstance(value, (str, int, float, bool)):
        if isinstance(value, float) and (value != value or value in (float('inf'), float('-inf'))):
            raise ExportError('non-finite number in authoritative metadata')
        return value
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, Mapping):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_json_safe(item) for item in value]
    raise ExportError(f'unsupported authoritative metadata value: {type(value).__name__}')


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        authority = FirestoreFacadeAuthority()
        manifest = export_authoritative_vectors(
            authority,
            uids=args.uids,
            all_users=bool(args.all_users),
            namespaces=args.namespace,
            output_dir=args.output_dir,
            sidecar=args.sidecar,
            allow_empty=bool(args.allow_empty),
        )
    except (ExportError, OSError, ValueError) as error:
        print(f'export failed: {error}', file=sys.stderr)
        return 2
    print(
        json.dumps(
            {
                'status': 'exported',
                'source_kind': manifest['source_kind'],
                'uid_count': manifest['uid_count'],
                'files': [
                    {'namespace': item['namespace'], 'record_count': item['record_count'], 'sha256': item['sha256']}
                    for item in manifest['files']
                ],
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
