#!/usr/bin/env python3
# LIFECYCLE: permanent
"""Export authoritative product rows for a vector projection rebuild.

The vector index is deliberately not consulted by this command.  The only
runtime dependency is the read-only Firestore-compatible facade exposed by
``database._client``.  In a self-host deployment that facade is backed by
PostgreSQL (``FIRESTORE_PG_DSN``); in the managed deployment it is backed by
Firestore.  The same source shape therefore drives a Pinecone-to-Qdrant
rebuild without carrying a Pinecone export forward as authority.

Each namespace is emitted as strict JSONL with exactly ``id``, ``content`` and
``metadata`` fields.  ``manifest.json`` binds each file's bytes, count and
source collection.  No vector values are emitted: embeddings are generated by
the explicitly configured migration runtime after this source export is
verified.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import stat
import sys
from collections.abc import Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass
from datetime import date, datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Protocol

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from models.structured import Structured
from scripts.source_write_freeze import SourceWriteFreezeError, canonical_endpoint, verify_lease

NAMESPACE_ORDER = (
    'ns1',
    'ns2',
    'workstream-association-v1',
    'ns_x',
    'ns3',
    'ns4',
    'ns_tchunks',
)
EXPORT_FORMAT = 'omi-authoritative-vector-export-v1'
MANIFEST_FORMAT = 'omi-authoritative-vector-export-manifest-v1'
MEMORY_MODES = ('canonical', 'legacy')
CANONICAL_MEMORY_SCHEMA_VERSION = 1
_RESTRICTED_SENSITIVITY_LABELS = frozenset(
    {
        'credential',
        'secret',
        'financial',
        'health',
        'intimate',
        'minor',
        'minors',
        'workplace_confidential',
        'identity_authentication',
    }
)
_RECORD_KEYS = frozenset({'id', 'content', 'metadata'})
_MANIFEST_REQUIRED_KEYS = frozenset(
    {
        'format',
        'export_format',
        'source_kind',
        'memory_mode',
        'uid_scope',
        'uids',
        'uid_sha256',
        'uid_count',
        'namespace_count',
        'empty_export_acknowledged',
        'namespaces',
        'files',
    }
)
_MANIFEST_OPTIONAL_KEYS = frozenset({'source_authority', 'source_freeze_lease_id'})
_MANIFEST_FILE_KEYS = frozenset({'namespace', 'path', 'source_collection', 'record_count', 'sha256'})
_SHA256 = set('0123456789abcdef')
_KNOWN_SOURCE_KINDS = frozenset({'firestore_facade', 'firestore_pg_facade'})


class ExportError(RuntimeError):
    """An operator input or authoritative-source contract failed."""


@dataclass(frozen=True)
class SourceDocument:
    id: str
    data: Mapping[str, Any]


class ReadOnlyAuthority(Protocol):
    """Minimal source contract; implementations must not expose writes."""

    source_kind: str

    def list_uids(self) -> Iterable[str]: ...

    def iter_user_documents(self, uid: str, collection: str) -> Iterable[SourceDocument]: ...


class FirestoreFacadeAuthority:
    """Read-only adapter over the repository's Firestore/PG compatibility seam."""

    def __init__(self, client: Any | None = None) -> None:
        if client is None:
            from database import _client as database_client

            client = database_client.db
        self._client = client
        self.source_kind = 'firestore_pg_facade' if os.getenv('FIRESTORE_PG_DSN', '').strip() else 'firestore_facade'

    def list_uids(self) -> Iterable[str]:
        for snapshot in self._client.collection('users').stream():
            uid = str(getattr(snapshot, 'id', '') or '').strip()
            if not uid:
                raise ExportError('authoritative users collection contains a blank document id')
            yield uid

    def iter_user_documents(self, uid: str, collection: str) -> Iterable[SourceDocument]:
        if not uid.strip():
            raise ExportError('uid must be non-empty')
        if not collection or '/' in collection:
            raise ExportError(f'unsupported collection {collection!r}')
        ref = self._client.collection('users').document(uid).collection(collection)
        for snapshot in ref.stream():
            document_id = str(getattr(snapshot, 'id', '') or '').strip()
            if not document_id:
                raise ExportError(f'{uid}/{collection} contains a blank document id')
            raw = snapshot.to_dict()
            if not isinstance(raw, Mapping):
                raise ExportError(f'{uid}/{collection}/{document_id} is not a JSON object')
            yield SourceDocument(id=document_id, data=dict(raw))


@dataclass(frozen=True)
class NamespaceSpec:
    collection: str | tuple[str, ...]


NAMESPACE_SPECS: dict[str, NamespaceSpec] = {
    'ns1': NamespaceSpec('conversations'),
    'ns2': NamespaceSpec('memory_items'),
    'workstream-association-v1': NamespaceSpec('workstreams'),
    'ns_x': NamespaceSpec('x_posts'),
    'ns3': NamespaceSpec('screen_activity'),
    'ns4': NamespaceSpec('action_items'),
    'ns_tchunks': NamespaceSpec('conversations'),
}
_AUTHORITY_NAMESPACE_ALIASES = {
    'conversations': 'ns1',
    'memories': 'ns2',
    'workstreams': 'workstream-association-v1',
    'screen_activity': 'ns3',
    'action_items': 'ns4',
    'transcript_chunks': 'ns_tchunks',
}


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    owner = parser.add_mutually_exclusive_group(required=True)
    owner.add_argument('--uid', action='append', dest='uids', help='Export one UID; may be repeated.')
    owner.add_argument('--all-users', action='store_true', help='Enumerate the authoritative users collection.')
    parser.add_argument(
        '--namespace',
        action='append',
        choices=NAMESPACE_ORDER,
        help='Export only this namespace; may be repeated (default: all seven).',
    )
    parser.add_argument('--output-dir', type=Path, required=True, help='New directory for namespace JSONL files.')
    parser.add_argument(
        '--sidecar',
        type=Path,
        help='Manifest path (default: OUTPUT_DIR/manifest.json). The file must not already exist.',
    )
    parser.add_argument(
        '--allow-empty',
        action='store_true',
        help='Explicitly acknowledge a namespace with no authoritative rows; default is fail-closed.',
    )
    parser.add_argument(
        '--memory-mode',
        choices=MEMORY_MODES,
        default='canonical',
        help='ns2 export contract; canonical is the safe default and legacy requires an explicit opt-in.',
    )
    parser.add_argument(
        '--source-project', required=True, help='Authoritative Firestore project id bound to the freeze lease.'
    )
    parser.add_argument(
        '--source-database',
        default='(default)',
        help='Authoritative Firestore database id bound to the freeze lease (default: (default)).',
    )
    parser.add_argument(
        '--source-endpoint',
        required=True,
        help='Credential-free source authority endpoint bound to the freeze lease.',
    )
    parser.add_argument(
        '--freeze-lease',
        type=Path,
        required=True,
        help='Mode-0600 HMAC source-write freeze lease required for every source read.',
    )
    return parser.parse_args(argv)


def export_authoritative_vectors(
    authority: ReadOnlyAuthority,
    *,
    uids: Iterable[str] | None,
    all_users: bool,
    namespaces: Iterable[str] | None,
    output_dir: Path,
    sidecar: Path | None = None,
    allow_empty: bool = False,
    memory_mode: str = 'canonical',
    source_read_guard: Any | None = None,
    source_authority: Mapping[str, str] | None = None,
    source_freeze_lease_id: str | None = None,
) -> dict[str, Any]:
    """Export selected source rows and return the same data written to sidecar."""

    normalized_memory_mode = _normalize_memory_mode(memory_mode)
    if source_read_guard is not None:
        source_read_guard()
    selected_uids = _resolve_uids(authority, uids=uids, all_users=all_users, source_read_guard=source_read_guard)
    selected_namespaces = _resolve_namespaces(namespaces)
    manifest_path = sidecar or output_dir / 'manifest.json'
    if manifest_path.exists():
        raise ExportError(f'manifest already exists: {manifest_path}')
    created_output_dir = _prepare_output_dir(output_dir)
    if manifest_path.parent != output_dir:
        manifest_path.parent.mkdir(parents=True, exist_ok=True)

    files: list[dict[str, Any]] = []
    generated_paths: list[Path] = []
    try:
        for namespace in selected_namespaces:
            records = _records_for_namespace(
                authority,
                namespace,
                selected_uids,
                memory_mode=normalized_memory_mode,
                source_read_guard=source_read_guard,
            )
            if not records and not allow_empty:
                raise ExportError(
                    f'authoritative export for namespace {namespace!r} is empty; '
                    'pass --allow-empty only after confirming that the namespace is intentionally unused'
                )
            filename = f'{_safe_filename(namespace)}.jsonl'
            output_path = output_dir / filename
            record_count, sha256 = _write_jsonl(output_path, records)
            generated_paths.append(output_path)
            files.append(
                {
                    'namespace': namespace,
                    'path': filename,
                    'source_collection': NAMESPACE_SPECS[namespace].collection,
                    'record_count': record_count,
                    'sha256': sha256,
                }
            )

        manifest: dict[str, Any] = {
            'format': MANIFEST_FORMAT,
            'export_format': EXPORT_FORMAT,
            'source_kind': authority.source_kind,
            'memory_mode': normalized_memory_mode,
            'uid_scope': 'all_users' if all_users else 'explicit',
            'uids': list(selected_uids),
            'uid_sha256': _uid_sha256(selected_uids),
            'uid_count': len(selected_uids),
            'namespace_count': len(selected_namespaces),
            'empty_export_acknowledged': bool(allow_empty),
            'namespaces': list(selected_namespaces),
            'files': files,
        }
        if source_authority is not None:
            manifest['source_authority'] = dict(source_authority)
        if source_freeze_lease_id is not None:
            manifest['source_freeze_lease_id'] = source_freeze_lease_id
        _write_manifest(manifest_path, manifest)
        return manifest
    except BaseException:
        # A manifest is the completion receipt. Never leave a partial export
        # which an operator could accidentally feed into the backfill CLI.
        for path in generated_paths:
            path.unlink(missing_ok=True)
        if manifest_path.parent == output_dir:
            manifest_path.unlink(missing_ok=True)
        if created_output_dir:
            try:
                output_dir.rmdir()
            except OSError:
                pass
        raise


def _prepare_output_dir(output_dir: Path) -> bool:
    """Create or validate a private, empty output directory.

    The export contains customer text and transcripts. Requiring a private
    directory makes the create-only contract safe even when the caller's
    process umask is permissive. The return value tells the caller whether it
    owns cleanup if a later namespace fails.
    """

    if output_dir.is_symlink():
        raise ExportError(f'output directory must not be a symlink: {output_dir}')
    if output_dir.exists():
        if not output_dir.is_dir():
            raise ExportError(f'output path exists and is not a directory: {output_dir}')
        if stat.S_IMODE(output_dir.stat().st_mode) & 0o077:
            raise ExportError(f'output directory must be private mode 0700 or stricter: {output_dir}')
        if any(output_dir.iterdir()):
            raise ExportError(f'output directory must be new or empty: {output_dir}')
        return False
    output_dir.mkdir(parents=True, exist_ok=False, mode=0o700)
    os.chmod(output_dir, 0o700)
    return True


def _resolve_uids(
    authority: ReadOnlyAuthority,
    *,
    uids: Iterable[str] | None,
    all_users: bool,
    source_read_guard: Any | None = None,
) -> tuple[str, ...]:
    if all_users:
        raw_uids = list(_guarded_iter(authority.list_uids(), source_read_guard))
    else:
        raw_uids = list(uids or ())
    normalized = [str(uid).strip() for uid in raw_uids]
    if any(not uid for uid in normalized):
        raise ExportError('UID values must be non-empty')
    unique = sorted(set(normalized))
    if len(unique) != len(normalized):
        raise ExportError('duplicate UID values are not allowed')
    if not unique:
        raise ExportError('at least one authoritative UID is required')
    return tuple(unique)


def _resolve_namespaces(namespaces: Iterable[str] | None) -> tuple[str, ...]:
    if namespaces is None:
        return NAMESPACE_ORDER
    raw_namespaces = tuple(str(namespace).strip() for namespace in namespaces)
    selected = tuple(dict.fromkeys(raw_namespaces))
    if not selected or any(namespace not in NAMESPACE_SPECS for namespace in selected):
        raise ExportError(f'namespace must be a duplicate-free subset of {NAMESPACE_ORDER!r}')
    if len(selected) != len(raw_namespaces):
        raise ExportError('duplicate namespace values are not allowed')
    return tuple(namespace for namespace in NAMESPACE_ORDER if namespace in selected)


def _uid_sha256(uids: Sequence[str]) -> str:
    return hashlib.sha256(('\n'.join(uids) + '\n').encode('utf-8')).hexdigest()


def _records_for_namespace(
    authority: ReadOnlyAuthority,
    namespace: str,
    uids: Sequence[str],
    *,
    memory_mode: str,
    source_read_guard: Any | None = None,
) -> tuple[dict[str, Any], ...]:
    records: list[dict[str, Any]] = []
    for uid in uids:
        if namespace == 'ns_tchunks':
            records.extend(_transcript_chunk_records(authority, uid, source_read_guard=source_read_guard))
            continue
        spec = NAMESPACE_SPECS[namespace]
        assert isinstance(spec.collection, str)
        for document in _guarded_iter(authority.iter_user_documents(uid, spec.collection), source_read_guard):
            record = _record_from_document(namespace, uid, document, memory_mode=memory_mode)
            if record is not None:
                records.append(record)
    records.sort(key=lambda record: (str(record['metadata'].get('uid', '')), str(record['id'])))
    return tuple(records)


def _record_from_document(
    namespace: str,
    uid: str,
    document: SourceDocument,
    *,
    memory_mode: str,
) -> dict[str, Any] | None:
    data = dict(document.data)
    if data.get('uid') not in (None, uid):
        raise ExportError(f'{uid}/{NAMESPACE_SPECS[namespace].collection}/{document.id} has a mismatched uid')
    if namespace == 'ns1':
        if _is_locked(data) or data.get('discarded') is True:
            return None
        structured = data.get('structured')
        structured_map = structured if isinstance(structured, Mapping) else {}
        content = _conversation_embedding_text(structured_map)
        if not content:
            return None
        metadata = {
            'uid': uid,
            'memory_id': document.id,
            'conversation_id': document.id,
            'created_at': _timestamp(data.get('created_at')),
        }
        return _record(f'{uid}-{document.id}', content, metadata)

    if namespace == 'ns2':
        if memory_mode == 'canonical':
            return _canonical_memory_record(uid, document)
        if data.get('status') not in (None, 'active'):
            return None
        content = _text(data.get('content'))
        if not content:
            return None
        memory_id = _text(data.get('memory_id')) or document.id
        metadata = {
            'uid': uid,
            'memory_id': memory_id,
            'category': _text(data.get('category')) or _text(data.get('predicate')),
            'status': _text(data.get('status')) or 'active',
            'tier': _enum_value(data.get('tier')),
            'subject_entity_id': _text(data.get('subject_entity_id')),
        }
        return _record(f'{uid}-{memory_id}', content, metadata)

    if namespace == 'workstream-association-v1':
        if data.get('status') not in (None, 'open'):
            return None
        workstream_id = _text(data.get('workstream_id')) or document.id
        objective = _text(data.get('objective'))
        state = _text(data.get('current_state_summary'))
        content = '\n'.join(
            part
            for part in (f'Objective: {objective}' if objective else '', f'Current state: {state}' if state else '')
            if part
        )
        if not content:
            return None
        generation = _integer(data.get('account_generation'), default=0)
        metadata = {
            'uid': uid,
            'workstream_id': workstream_id,
            'status': 'open',
            'account_generation': generation,
            'schema_version': 1,
        }
        return _record(f'{uid}:workstream:{generation}:{workstream_id}', content, metadata)

    if namespace == 'ns_x':
        content = _text(data.get('text')) or _text(data.get('content'))
        if not content:
            return None
        post_id = _text(data.get('id')) or document.id
        metadata = {
            'uid': uid,
            'post_id': post_id,
            'kind': _text(data.get('kind')) or 'tweet',
            'created_at': _timestamp(data.get('created_at')),
        }
        return _record(f'{uid}-x-{post_id}', content, metadata)

    if namespace == 'ns3':
        content = _text(data.get('ocrText')) or _text(data.get('ocr_text'))
        if not content:
            return None
        screenshot_id = _text(data.get('storageId')) or _text(data.get('storage_id')) or document.id
        metadata = {
            'uid': uid,
            'screenshot_id': screenshot_id,
            'timestamp': _timestamp(data.get('timestamp')),
            'appName': _text(data.get('appName')),
        }
        return _record(f'{uid}-sa-{screenshot_id}', content, metadata)

    if namespace == 'ns4':
        if data.get('deleted') is True or data.get('status') in ('cancelled', 'superseded'):
            return None
        content = _text(data.get('description'))
        if not content:
            return None
        action_item_id = _text(data.get('id')) or document.id
        metadata = {
            'uid': uid,
            'action_item_id': action_item_id,
            'status': _text(data.get('status')) or ('completed' if data.get('completed') is True else 'active'),
            'created_at': _timestamp(data.get('created_at')),
        }
        return _record(f'{uid}-ai-{action_item_id}', content, metadata)

    raise ExportError(f'unsupported namespace {namespace!r}')


def _canonical_memory_record(uid: str, document: SourceDocument) -> dict[str, Any] | None:
    """Build the metadata contract consumed by canonical ns2 memory search.

    Legacy ``memory_items`` rows are deliberately not guessed into this shape.
    A canonical vector without revision/source/ledger lineage is not safe to
    hydrate, so the default export fails closed instead of creating a vector
    that the canonical parser will later reject.
    """
    data = dict(document.data)
    status = _text(_enum_value(data.get('status')))
    if status not in ('active', ''):
        return None
    content = _text(data.get('content'))
    if not content:
        return None
    memory_id = _text(data.get('memory_id')) or document.id
    if _text(data.get('uid')) not in ('', uid):
        raise ExportError(f'{uid}/memory_items/{document.id} has a mismatched uid')

    required_strings = (
        'tier',
        'processing_state',
        'source_state',
        'visibility',
        'source_commit_id',
        'content_hash',
        'ledger_commit_id',
    )
    missing = [key for key in required_strings if not _text(_enum_value(data.get(key)))]
    if missing:
        raise ExportError(f'{uid}/memory_items/{document.id} is missing canonical memory lineage: {", ".join(missing)}')
    labels = data.get('sensitivity_labels')
    if not isinstance(labels, (list, tuple, set)) or any(not isinstance(label, str) for label in labels):
        raise ExportError(f'{uid}/memory_items/{document.id} sensitivity_labels must be a string list')
    normalized_labels = sorted({label.strip().lower() for label in labels if label.strip()})
    updated_at = _canonical_timestamp(data.get('updated_at'), uid=uid, memory_id=memory_id)
    item_revision = _integer(data.get('item_revision'), default=0)
    if item_revision < 1:
        raise ExportError(f'{uid}/memory_items/{document.id} item_revision must be positive')
    account_generation = _integer(data.get('account_generation'), default=-1)
    if account_generation < 0:
        raise ExportError(f'{uid}/memory_items/{document.id} account_generation must be non-negative')
    metadata = {
        'memory_schema_version': CANONICAL_MEMORY_SCHEMA_VERSION,
        'memory_layer': _text(_enum_value(data.get('tier'))),
        'uid': uid,
        'memory_id': memory_id,
        'status': status or 'active',
        'processing_state': _text(_enum_value(data.get('processing_state'))),
        'source_state': _text(_enum_value(data.get('source_state'))),
        'visibility': _text(data.get('visibility')),
        'sensitivity_labels': normalized_labels,
        'restricted_sensitivity': bool(set(normalized_labels).intersection(_RESTRICTED_SENSITIVITY_LABELS)),
        'account_generation': account_generation,
        'item_revision': item_revision,
        'source_commit_id': _text(data.get('source_commit_id')),
        'content_hash': _text(data.get('content_hash')),
        # The ledger commit is the authoritative projection fence used by the
        # live canonical upsert path. It is not inferred from a vector id.
        'projection_commit_id': _text(data.get('ledger_commit_id')),
        'vector_updated_at': updated_at,
    }
    return _record(f'{uid}-{memory_id}', content, metadata)


def _conversation_embedding_text(structured: Mapping[str, Any]) -> str:
    """Use the exact text representation used by the production vector writer.

    ``save_structured_vector`` embeds ``str(conversation.structured)``.  The
    migration exporter must not substitute a title/overview shortcut: doing so
    would produce a different vector for the same authoritative document.
    """

    try:
        value = Structured.model_validate(dict(structured))
    except Exception as error:
        raise ExportError('conversation structured payload cannot be validated for vector export') from error
    return str(value).strip()


def _transcript_chunk_records(
    authority: ReadOnlyAuthority,
    uid: str,
    *,
    source_read_guard: Any | None = None,
) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for document in _guarded_iter(authority.iter_user_documents(uid, 'conversations'), source_read_guard):
        data = dict(document.data)
        if _is_locked(data) or data.get('discarded') is True:
            continue
        data = _decode_conversation_for_export(uid, data)
        segments = data.get('transcript_segments')
        if not isinstance(segments, list):
            # Encrypted/compressed transcripts are intentionally not guessed at
            # this generic authority boundary. The production conversation
            # reader must expose decoded segments before this namespace is
            # exported; silently indexing an empty transcript is unsafe.
            if segments:
                raise ExportError(
                    f'{uid}/conversations/{document.id} transcript_segments are not decoded; '
                    'run the export with the repository conversation facade'
                )
            continue
        started_at = data.get('started_at') or data.get('created_at')
        chunks = _build_chunks(segments, started_at)
        for chunk in chunks:
            index = int(chunk['chunk_index'])
            records.append(
                _record(
                    f'{uid}-{document.id}-c{index}',
                    str(chunk['text']),
                    {
                        'uid': uid,
                        'conversation_id': document.id,
                        'chunk_index': index,
                        'created_at': int(chunk['created_at']),
                    },
                )
            )
    return records


def _guarded_iter(values: Iterable[Any], guard: Any | None) -> Iterator[Any]:
    """Advance a lazy authority iterator only while the source lease is live."""

    iterator = iter(values)
    while True:
        if guard is not None:
            guard()
        try:
            yield next(iterator)
        except StopIteration:
            return


def _decode_conversation_for_export(uid: str, data: dict[str, Any]) -> dict[str, Any]:
    """Decode the repository's compressed/encrypted transcript at the source boundary."""
    raw_segments = data.get('transcript_segments')
    if not raw_segments or isinstance(raw_segments, list):
        return data
    try:
        from database.conversations import _prepare_conversation_for_read

        decoded = _prepare_conversation_for_read(data, uid)
    except Exception as error:
        raise ExportError(f'conversation transcript is not decoded for uid {uid}') from error
    if not isinstance(decoded, Mapping):
        raise ExportError(f'conversation transcript decode returned an invalid document for uid {uid}')
    return dict(decoded)


def _build_chunks(segments: list[Any], started_at: Any) -> list[dict[str, Any]]:
    """Small dependency-free equivalent of the production chunking contract."""
    lines: list[str] = []
    for segment in segments:
        if not isinstance(segment, Mapping):
            raise ExportError('transcript segment must be an object')
        text = _text(segment.get('text'))
        if not text:
            continue
        label = (
            'User'
            if segment.get('is_user')
            else (f"Speaker {segment.get('speaker_id')}" if segment.get('speaker_id') is not None else 'Speaker')
        )
        lines.append(f'{label}: {text}')
    if not lines:
        return []
    date_header = ''
    created_at = _timestamp(started_at)
    if isinstance(started_at, datetime):
        date_header = f'[Conversation on {started_at.strftime("%d %b %Y, %H:%M")}]\n'
    chunks: list[dict[str, Any]] = []
    position = 0
    index = 0
    while position < len(lines):
        chunks.append(
            {
                'text': date_header + '\n'.join(lines[position : position + 8]),
                'created_at': created_at,
                'chunk_index': index,
            }
        )
        if position + 8 >= len(lines):
            break
        position += 6
        index += 1
    return chunks


def _record(record_id: str, content: str, metadata: Mapping[str, Any]) -> dict[str, Any]:
    if not record_id.strip() or not content.strip():
        raise ExportError('authoritative vector record id/content must be non-empty')
    normalized = {key: value for key, value in metadata.items() if value is not None and value != ''}
    record = {'id': record_id, 'content': content, 'metadata': _json_safe(normalized)}
    if set(record) != _RECORD_KEYS:
        raise ExportError('internal exporter produced a non-strict record')
    return record


def _write_jsonl(path: Path, records: Iterable[Mapping[str, Any]]) -> tuple[int, str]:
    digest = hashlib.sha256()
    count = 0
    try:
        with _open_private_file(path, binary=True) as handle:
            for value in records:
                if set(value) != _RECORD_KEYS:
                    raise ExportError(f'internal exporter produced invalid JSONL record for {path.name}')
                line = (
                    json.dumps(
                        value, ensure_ascii=False, sort_keys=True, separators=(',', ':'), allow_nan=False
                    ).encode('utf-8')
                    + b'\n'
                )
                handle.write(line)
                digest.update(line)
                count += 1
    except FileExistsError as error:
        raise ExportError(f'output file already exists: {path}') from error
    except BaseException:
        path.unlink(missing_ok=True)
        raise
    return count, digest.hexdigest()


def _write_manifest(path: Path, manifest: Mapping[str, Any]) -> None:
    payload = json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2, allow_nan=False) + '\n'
    try:
        with _open_private_file(path, binary=False) as handle:
            handle.write(payload)
    except FileExistsError as error:
        raise ExportError(f'manifest already exists: {path}') from error
    except BaseException:
        path.unlink(missing_ok=True)
        raise


def verify_authoritative_export_manifest(
    manifest_path: Path,
    *,
    records_path: Path,
    namespace: str,
    memory_mode: str,
    allow_empty: bool = False,
) -> dict[str, Any]:
    """Verify that one JSONL input is the output of this authority exporter.

    The vector projection CLI accepts JSONL for testability, but production
    backfills must bind that input to the source export manifest.  This check
    validates the manifest schema, source evidence, exact file name, mode and
    count/hash before embeddings or target writes begin.  It intentionally
    does not trust a vector index or a caller-supplied record count.
    """

    _require_private_regular_file(manifest_path, 'authority export manifest')
    _require_private_regular_file(records_path, 'authority export records')
    try:
        raw = manifest_path.read_bytes()
        value = json.loads(raw, parse_constant=lambda constant: _reject_json_constant(constant))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ExportError('authority export manifest is not valid UTF-8 JSON') from error
    if not isinstance(value, dict):
        raise ExportError('authority export manifest must be a JSON object')
    unknown = set(value) - (_MANIFEST_REQUIRED_KEYS | _MANIFEST_OPTIONAL_KEYS)
    missing = _MANIFEST_REQUIRED_KEYS - set(value)
    if missing or unknown:
        raise ExportError(
            'authority export manifest fields are invalid'
            + (f' (missing={sorted(missing)})' if missing else '')
            + (f' (unknown={sorted(unknown)})' if unknown else '')
        )
    if value['format'] != MANIFEST_FORMAT or value['export_format'] != EXPORT_FORMAT:
        raise ExportError('authority export manifest format is unsupported')
    source_kind = value['source_kind']
    if not isinstance(source_kind, str) or source_kind not in _KNOWN_SOURCE_KINDS:
        raise ExportError('authority export manifest source_kind is not a repository authority')
    normalized_memory_mode = _normalize_memory_mode(str(value['memory_mode']))
    if normalized_memory_mode != _normalize_memory_mode(memory_mode):
        raise ExportError('authority export manifest memory_mode does not match the projection request')
    source_authority = value.get('source_authority')
    if not isinstance(source_authority, dict) or set(source_authority) != {'project', 'database', 'endpoint'}:
        raise ExportError('authority export manifest source authority evidence is missing or invalid')
    if any(not isinstance(source_authority[key], str) or not source_authority[key].strip() for key in source_authority):
        raise ExportError('authority export manifest source authority evidence is invalid')
    try:
        canonical_endpoint(source_authority['endpoint'])
    except SourceWriteFreezeError as error:
        raise ExportError('authority export manifest source endpoint evidence is invalid') from error
    freeze_lease_id = value.get('source_freeze_lease_id')
    if not isinstance(freeze_lease_id, str) or not freeze_lease_id.strip():
        raise ExportError('authority export manifest source freeze evidence is missing')

    raw_uids = value['uids']
    if not isinstance(raw_uids, list) or any(not isinstance(uid, str) or not uid.strip() for uid in raw_uids):
        raise ExportError('authority export manifest UID inventory is invalid')
    uids = [uid.strip() for uid in raw_uids]
    if uids != sorted(set(uids)):
        raise ExportError('authority export manifest UID inventory is not sorted and duplicate-free')
    if value['uid_scope'] not in {'all_users', 'explicit'}:
        raise ExportError('authority export manifest UID scope is invalid')
    if value['uid_count'] != len(uids) or value['uid_sha256'] != _uid_sha256(uids):
        raise ExportError('authority export manifest UID inventory hash/count is invalid')
    raw_namespaces = value['namespaces']
    if (
        not isinstance(raw_namespaces, list)
        or any(not isinstance(item, str) for item in raw_namespaces)
        or any(item not in NAMESPACE_SPECS for item in raw_namespaces)
        or len(raw_namespaces) != len(set(raw_namespaces))
        or tuple(raw_namespaces)
        != tuple(namespace_name for namespace_name in NAMESPACE_ORDER if namespace_name in raw_namespaces)
        or value['namespace_count'] != len(raw_namespaces)
    ):
        raise ExportError('authority export manifest namespace inventory is invalid')
    authority_namespace = _AUTHORITY_NAMESPACE_ALIASES.get(namespace, namespace)
    if authority_namespace not in raw_namespaces:
        raise ExportError(f'authority export manifest does not contain namespace {namespace!r}')
    raw_files = value['files']
    if not isinstance(raw_files, list) or len(raw_files) != len(raw_namespaces):
        raise ExportError('authority export manifest file inventory is invalid')
    selected: dict[str, Any] | None = None
    file_namespaces: set[str] = set()
    for item in raw_files:
        if not isinstance(item, dict) or set(item) != _MANIFEST_FILE_KEYS:
            raise ExportError('authority export manifest contains an invalid file entry')
        item_namespace = item['namespace']
        item_path = item['path']
        if item_namespace not in raw_namespaces or not isinstance(item_path, str) or Path(item_path).name != item_path:
            raise ExportError('authority export manifest contains an unsafe file mapping')
        if item['source_collection'] != NAMESPACE_SPECS[item_namespace].collection:
            raise ExportError(f'authority export manifest source collection does not match {item_namespace!r}')
        if item_namespace in file_namespaces:
            raise ExportError(f'authority export manifest repeats namespace {item_namespace!r}')
        file_namespaces.add(item_namespace)
        if (
            not isinstance(item['record_count'], int)
            or isinstance(item['record_count'], bool)
            or item['record_count'] < 0
            or not isinstance(item['sha256'], str)
            or len(item['sha256']) != 64
            or set(item['sha256']) - _SHA256
        ):
            raise ExportError('authority export manifest file count/hash is invalid')
        if item_namespace == authority_namespace:
            if selected is not None:
                raise ExportError(f'authority export manifest repeats namespace {namespace!r}')
            selected = item
    if file_namespaces != set(raw_namespaces):
        raise ExportError('authority export manifest file namespaces do not match its namespace inventory')
    if selected is None or selected['path'] != records_path.name:
        raise ExportError(f'authority export manifest path does not match {records_path.name!r}')
    record_bytes = records_path.read_bytes()
    actual_count = len([line for line in record_bytes.splitlines() if line.strip()])
    if actual_count != selected['record_count'] or hashlib.sha256(record_bytes).hexdigest() != selected['sha256']:
        raise ExportError('authority export records do not match the manifest count/hash')
    if actual_count == 0 and (not allow_empty or value['empty_export_acknowledged'] is not True):
        raise ExportError('empty authority export requires the manifest acknowledgement and --allow-empty')
    if not isinstance(value['empty_export_acknowledged'], bool):
        raise ExportError('authority export manifest empty acknowledgement is invalid')
    return {
        'manifest_sha256': hashlib.sha256(raw).hexdigest(),
        'source_kind': source_kind,
        'source_authority': dict(source_authority),
        'source_freeze_lease_id': freeze_lease_id,
        'record_count': actual_count,
        'records_sha256': selected['sha256'],
    }


def _require_private_regular_file(path: Path, label: str) -> None:
    if path.is_symlink() or not path.is_file():
        raise ExportError(f'{label} is missing or is not a regular file: {path}')
    if stat.S_IMODE(path.stat().st_mode) & 0o077:
        raise ExportError(f'{label} must be mode 0600 or stricter: {path}')


def _reject_json_constant(constant: str) -> Any:
    raise json.JSONDecodeError(f'non-standard numeric constant {constant}', constant, 0)


def _open_private_file(path: Path, *, binary: bool):
    """Open a new file exclusively with mode 0600, rejecting symlink races."""

    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    if hasattr(os, 'O_NOFOLLOW'):
        flags |= os.O_NOFOLLOW
    try:
        descriptor = os.open(path, flags, 0o600)
    except FileExistsError:
        raise
    mode = 'wb' if binary else 'w'
    return os.fdopen(descriptor, mode, encoding=None if binary else 'utf-8')


def _safe_filename(namespace: str) -> str:
    return namespace.replace('-', '_')


def _text(value: Any) -> str:
    return value.strip() if isinstance(value, str) else ''


def _normalize_memory_mode(value: str) -> str:
    normalized = str(value).strip().lower()
    if normalized not in MEMORY_MODES:
        raise ExportError(f'memory mode must be one of {MEMORY_MODES!r}')
    return normalized


def _canonical_timestamp(value: Any, *, uid: str, memory_id: str) -> str:
    if value is None:
        raise ExportError(f'{uid}/memory_items/{memory_id} updated_at is required for canonical vector metadata')
    if isinstance(value, bool):
        raise ExportError(f'{uid}/memory_items/{memory_id} updated_at is invalid')
    if isinstance(value, datetime):
        if value.tzinfo is None or value.utcoffset() is None:
            raise ExportError(f'{uid}/memory_items/{memory_id} updated_at must be timezone-aware')
        return value.isoformat()
    if isinstance(value, date):
        return datetime(value.year, value.month, value.day, tzinfo=timezone.utc).isoformat()
    if isinstance(value, str):
        try:
            parsed = datetime.fromisoformat(value.strip().replace('Z', '+00:00'))
        except ValueError as error:
            raise ExportError(f'{uid}/memory_items/{memory_id} updated_at is invalid') from error
        if parsed.tzinfo is None or parsed.utcoffset() is None:
            raise ExportError(f'{uid}/memory_items/{memory_id} updated_at must be timezone-aware')
        return parsed.isoformat()
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        try:
            return datetime.fromtimestamp(float(value), tz=timezone.utc).isoformat()
        except (OverflowError, OSError, ValueError) as error:
            raise ExportError(f'{uid}/memory_items/{memory_id} updated_at is invalid') from error
    raise ExportError(f'{uid}/memory_items/{memory_id} updated_at is invalid')


def _enum_value(value: Any) -> Any:
    return value.value if isinstance(value, Enum) else value


def _integer(value: Any, *, default: int) -> int:
    if value is None:
        return default
    if isinstance(value, bool):
        raise ExportError('boolean cannot be used as an integer authority field')
    try:
        return int(value)
    except (TypeError, ValueError) as error:
        raise ExportError(f'invalid integer authority field: {value!r}') from error


def _timestamp(value: Any) -> int:
    if value is None:
        return 0
    if isinstance(value, bool):
        raise ExportError('boolean cannot be used as a timestamp authority field')
    if isinstance(value, datetime):
        normalized = value if value.tzinfo is not None else value.replace(tzinfo=timezone.utc)
        return int(normalized.timestamp())
    if isinstance(value, date):
        return int(datetime(value.year, value.month, value.day, tzinfo=timezone.utc).timestamp())
    if isinstance(value, str):
        raw = value.strip()
        try:
            parsed = datetime.fromisoformat(raw.replace('Z', '+00:00'))
        except ValueError:
            parsed = None
        if parsed is not None:
            normalized = parsed if parsed.tzinfo is not None else parsed.replace(tzinfo=timezone.utc)
            return int(normalized.timestamp())
        value = raw
    try:
        return int(value)
    except (TypeError, ValueError) as error:
        raise ExportError(f'invalid timestamp authority field: {value!r}') from error


def _is_locked(data: Mapping[str, Any]) -> bool:
    return data.get('is_locked') is True or data.get('data_protection_level') == 'enhanced'


def _json_safe(value: Any) -> Any:
    value = _enum_value(value)
    if value is None or isinstance(value, (str, int, float, bool)):
        if isinstance(value, float) and (value != value or value in (float('inf'), float('-inf'))):
            raise ExportError('non-finite number in authoritative metadata')
        return value
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, Mapping):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_json_safe(item) for item in value]
    raise ExportError(f'unsupported authoritative metadata value: {type(value).__name__}')


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        authority = FirestoreFacadeAuthority()
        source_endpoint = canonical_endpoint(args.source_endpoint)
        lease = verify_lease(
            args.freeze_lease,
            source_project=args.source_project,
            source_database=args.source_database,
            source_endpoint=source_endpoint,
            required_scopes={'firestore'},
        )

        def verify_source_write_freeze() -> None:
            verify_lease(
                args.freeze_lease,
                source_project=args.source_project,
                source_database=args.source_database,
                source_endpoint=source_endpoint,
                required_scopes={'firestore'},
            )

        manifest = export_authoritative_vectors(
            authority,
            uids=args.uids,
            all_users=bool(args.all_users),
            namespaces=args.namespace,
            output_dir=args.output_dir,
            sidecar=args.sidecar,
            allow_empty=bool(args.allow_empty),
            memory_mode=args.memory_mode,
            source_read_guard=verify_source_write_freeze,
            source_authority={
                'project': args.source_project,
                'database': args.source_database,
                'endpoint': source_endpoint,
            },
            source_freeze_lease_id=str(lease['lease_id']),
        )
    except (ExportError, SourceWriteFreezeError, OSError, ValueError) as error:
        print(f'export failed: {error}', file=sys.stderr)
        return 2
    print(
        json.dumps(
            {
                'status': 'exported',
                'source_kind': manifest['source_kind'],
                'uid_count': manifest['uid_count'],
                'files': [
                    {'namespace': item['namespace'], 'record_count': item['record_count'], 'sha256': item['sha256']}
                    for item in manifest['files']
                ],
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
