#!/usr/bin/env python3
"""Check generated bytes and inspect explicit brand-facing text surfaces.

Default source scans are heuristics, including Web/TSX strings and JSX text.
--build-root/--runtime-root additionally scan decoded UTF-8 artifact metadata
and runtime exports. Binaries, images, signatures and live UI are not inspected;
coverage reports list unscanned files. --release requires both export roots and
complete generators, skips source heuristics, and cannot use a baseline.

omi-upstream reports self-check match counts; other brands fail on matches.
A source baseline never overrides invalid manifests or stale generated bytes.
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from yaml_lite import load_yaml as _load_yaml  # noqa: E402
from manifest import ManifestError, load_manifest  # noqa: E402
from apply import ApplyError, CATEGORIES, assess  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
LEXICON_PATH = Path(__file__).resolve().parent / "lexicon.yaml"
ALLOW_PATH = REPO_ROOT / "brand/_allow.yaml"
UPSTREAM_BRAND_ID = "omi-upstream"

# Path globs for each named surface in §6. Deliberately explicit rather than
# "scan everything" -- deploy/, backend/fork/, scripts/, dev/ are fork
# infrastructure and design docs, not brand-facing product surfaces, and
# scanning them would bury real leaks in noise from files that are ABOUT the
# brand system rather than PART OF the branded product.
SURFACE_GLOBS: dict[str, tuple[str, ...]] = {
    "mobile_l10n": ("app/lib/l10n/*.arb",),
    "mobile_source": ("app/lib/**/*.dart",),
    "macos_source": ("desktop/macos/Desktop/**/*.swift",),
    "macos_plist": ("desktop/macos/Desktop/**/Info.plist",),
    "windows_source": ("desktop/windows/src/**/*.ts", "desktop/windows/src/**/*.tsx"),
    "web_source": ("web/app/src/**/*.ts", "web/app/src/**/*.tsx", "web/app/src/**/*.js", "web/app/src/**/*.jsx"),
    "backend_prompts": (
        "backend/utils/llm/**/*.py",
        "backend/llm_gateway/**/*.py",
    ),
    "backend_templates": ("backend/templates/*.html",),
    "docs_config": ("docs/docs.json",),
    "firmware_identity": (
        "omi/firmware/omi/omi.conf",
        "omi/firmware/omi/src/lib/core/nfc.c",
    ),
    "build_config": ("config/public-build-values.json",),
    "dockerfiles": ("**/Dockerfile*",),
}

# service_identifiers, scanned everywhere the code surfaces above are
# scanned -- never against real secret VALUES, only public-safe hostnames
# and project identifiers (lexicon.yaml's own note explains why).
SERVICE_IDENTIFIER_KEY = "service_identifiers"


@dataclass
class Match:
    surface: str
    path: str
    line: int
    word: str
    context: str


@dataclass
class Exemption:
    glob: str
    words: frozenset[str] | None
    reason: str


def load_yaml(path: Path) -> dict:
    return _load_yaml(path) or {}


def load_exemptions() -> list[Exemption]:
    if not ALLOW_PATH.exists():
        return []
    data = load_yaml(ALLOW_PATH)
    out = []
    for glob, entry in data.get("exemptions", {}).items():
        words = entry.get("words")
        out.append(Exemption(glob=glob, words=frozenset(words) if words else None, reason=entry["reason"]))
    return out


def is_exempt(path: str, word: str, exemptions: list[Exemption]) -> bool:
    for ex in exemptions:
        if fnmatch.fnmatch(path, ex.glob) or path == ex.glob:
            if ex.words is None or word in ex.words:
                return True
    return False


def iter_surface_files(repo_root: Path = REPO_ROOT) -> dict[str, list[Path]]:
    out: dict[str, list[Path]] = {}
    for surface, globs in SURFACE_GLOBS.items():
        found: list[Path] = []
        for glob in globs:
            found.extend(repo_root.glob(glob))
        out[surface] = sorted(set(found))
    return out


_SWIFT_LITERAL_RE = re.compile(r"""(?:Text|Button|Label|\.alert|\.help)\([^)]*?['"]([^'"]*)['"]""", re.DOTALL)
_ARB_VALUE_RE = re.compile(r'"[^"]+"\s*:\s*"([^"]*)"')
_PLIST_STRING_RE = re.compile(r"<string>([^<]*)</string>")


def _lines_matching(text: str, patterns: list[re.Pattern]) -> list[tuple[int, str]]:
    out = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        for pattern in patterns:
            for m in pattern.finditer(line):
                out.append((lineno, m.group(1) if m.groups() else line))
    return out


# A bounded source lexer: quoted/template literals, JSX text and attributes.
# It intentionally does not execute JS or claim to evaluate dynamic expressions.
_JS_TOKEN_RE = re.compile(
    r"//[^\n]*|/\*.*?\*/|(?P<quote>['\"`])(?P<literal>(?:\\.|(?!(?P=quote)).)*)(?P=quote)|>(?P<jsx>[^<>{}]+)<", re.S
)


def extract_js_strings(text: str) -> list[tuple[int, str]]:
    candidates = []
    for match in _JS_TOKEN_RE.finditer(text):
        value = match.group("literal") if match.group("quote") else match.group("jsx")
        if value is None:
            continue
        # Decode common JS source escapes so 'Om\\u0069' is visible to the scan.
        value = re.sub(
            r"\\u([0-9a-fA-F]{4})|\\x([0-9a-fA-F]{2})", lambda m: chr(int(m.group(1) or m.group(2), 16)), value
        )
        candidates.append((text.count("\n", 0, match.start()) + 1, value))
    return candidates


def extract_candidate_strings(surface: str, path: Path) -> list[tuple[int, str]]:
    """Return (line_number, extracted_string) pairs worth lexicon-checking.

    For surfaces without a narrower extractor (templates, JSON config,
    firmware source, Dockerfiles), the whole line is the candidate -- these
    are already small, brand-relevant files where a substring hit is
    meaningful without extracting a specific literal first.
    """
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return []
    if surface == "mobile_l10n":
        return _lines_matching(text, [_ARB_VALUE_RE])
    if surface == "macos_source":
        return _lines_matching(text, [_SWIFT_LITERAL_RE])
    if surface in ("windows_source", "web_source"):
        return extract_js_strings(text)
    if surface == "macos_plist":
        return _lines_matching(text, [_PLIST_STRING_RE])
    if surface == "mobile_source":
        # Dart's own user-facing-string shape (Text(...)) mirrors Swift's
        # closely enough to reuse the same heuristic literal extractor.
        return _lines_matching(text, [_SWIFT_LITERAL_RE, _ARB_VALUE_RE])
    return [(i, line) for i, line in enumerate(text.splitlines(), start=1)]


def scan(brand_id: str, exemptions: list[Exemption], repo_root: Path = REPO_ROOT) -> list[Match]:
    lexicon = load_yaml(LEXICON_PATH)
    words = list(lexicon.get("words", []))
    substrings = list(lexicon.get("domains", [])) + list(lexicon.get("identifiers", []))
    word_re = re.compile(r"\b(" + "|".join(re.escape(w) for w in words) + r")\b", re.IGNORECASE) if words else None

    matches: list[Match] = []
    for surface, paths in iter_surface_files(repo_root).items():
        for path in paths:
            rel = str(path.relative_to(repo_root))
            for lineno, candidate in extract_candidate_strings(surface, path):
                if word_re:
                    for m in word_re.finditer(candidate):
                        hit = m.group(1)
                        if is_exempt(rel, hit, exemptions):
                            continue
                        matches.append(Match(surface, rel, lineno, hit, candidate.strip()[:120]))
                for sub in substrings:
                    if sub.lower() in candidate.lower():
                        if is_exempt(rel, sub, exemptions):
                            continue
                        matches.append(Match(surface, rel, lineno, sub, candidate.strip()[:120]))
    return matches


def scan_service_identifiers(repo_root: Path = REPO_ROOT) -> list[Match]:
    lexicon = load_yaml(LEXICON_PATH)
    identifiers = list(lexicon.get(SERVICE_IDENTIFIER_KEY, []))
    if not identifiers:
        return []
    exemptions = load_exemptions()
    matches: list[Match] = []
    for surface, paths in iter_surface_files(repo_root).items():
        for path in paths:
            rel = str(path.relative_to(repo_root))
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            for lineno, line in enumerate(text.splitlines(), start=1):
                for identifier in identifiers:
                    if identifier.lower() in line.lower() and not is_exempt(rel, identifier, exemptions):
                        matches.append(Match(f"{surface}:service-id", rel, lineno, identifier, line.strip()[:120]))
    return matches


TEXT_OUTPUT_SUFFIXES = frozenset(
    (".json", ".html", ".htm", ".js", ".css", ".svg", ".plist", ".xml", ".txt", ".md", ".ts", ".tsx")
)


def scan_exports(root: Path, surface: str) -> tuple[list[Match], dict]:
    """Scan decoded build metadata/text or runtime exports, never executable binaries."""
    if not root.is_dir():
        raise ApplyError(f"{surface} root is not a directory: {root}")
    lexicon = load_yaml(LEXICON_PATH)
    words = list(lexicon.get("words", []))
    literals = (
        list(lexicon.get("domains", []))
        + list(lexicon.get("identifiers", []))
        + list(lexicon.get(SERVICE_IDENTIFIER_KEY, []))
    )
    pattern = re.compile(r"\b(" + "|".join(re.escape(w) for w in words) + r")\b", re.I)
    matches = []
    exemptions = load_exemptions()
    inspected = []
    unscanned = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        relative = str(path.relative_to(root))
        if path.is_symlink() or path.suffix.lower() not in TEXT_OUTPUT_SUFFIXES:
            unscanned.append(relative)
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeError, OSError):
            unscanned.append(relative)
            continue
        inspected.append(relative)
        for lineno, line in enumerate(text.splitlines(), 1):
            hits = [m.group(0) for m in pattern.finditer(line)] + [
                word for word in literals if word.lower() in line.lower()
            ]
            matches.extend(
                Match(surface, relative, lineno, word, line.strip()[:120])
                for word in hits
                if not is_exempt(f"{surface}/{relative}", word, exemptions)
            )
    if not inspected:
        raise ApplyError(f"{surface} root has no supported text exports: {root}")
    return matches, {
        "root": str(root),
        "inspected": inspected,
        "unscanned": unscanned,
        "scope": "UTF-8 text/metadata only; no binary, image, signature or live UI verification",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--brand")
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--output-root", type=Path, default=REPO_ROOT, help="generated source/build overlay to compare")
    parser.add_argument("--source-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--only", action="append", choices=CATEGORIES)
    parser.add_argument(
        "--release", action="store_true", help="require complete generators plus build and runtime text exports"
    )
    parser.add_argument("--build-root", type=Path)
    parser.add_argument("--runtime-root", type=Path)
    parser.add_argument("--baseline", type=Path, help="ratchet source matches; never bypasses invalid/stale generation")
    parser.add_argument("--base", default="upstream/main", help="reserved; scan is never diff-scoped")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    try:
        manifest = load_manifest(args.brand, REPO_ROOT, args.manifest)
        brand = manifest["brand"]["id"]
        self_check = brand == UPSTREAM_BRAND_ID
        generation = assess(manifest, args.output_root, args.only, args.release)
        if args.release and (args.baseline or not args.build_root or not args.runtime_root):
            raise ApplyError("--release requires --build-root and --runtime-root and forbids --baseline")
        lexicon_matches = [] if args.release else scan(brand, load_exemptions(), args.source_root)
        service_matches = [] if self_check or args.release else scan_service_identifiers(args.source_root)
        exports = {}
        for surface, root in (("build", args.build_root), ("runtime", args.runtime_root)):
            if root:
                matches, exports[surface] = scan_exports(root, surface)
                lexicon_matches.extend(matches)
        total = len(lexicon_matches) + len(service_matches)
        ratchet_ok = True
        if args.baseline:
            previous = int(args.baseline.read_text().strip()) if args.baseline.exists() else total
            ratchet_ok = total <= previous
            if ratchet_ok and generation["ok"]:
                args.baseline.parent.mkdir(parents=True, exist_ok=True)
                args.baseline.write_text(f"{total}\n")
        ok = generation["ok"] and ratchet_ok and (self_check or bool(args.baseline) or total == 0)
        report = {
            "brand": brand,
            "self_check": self_check,
            "ok": ok,
            "lexicon_matches": len(lexicon_matches),
            "service_identifier_matches": len(service_matches),
            "apply_check_clean": not generation["drift"],
            "generation": generation,
            "source_scanned": not args.release,
            "source_scope": "heuristic string extraction; no executed templates/dynamic values",
            "exports": exports,
            "matches": [m.__dict__ for m in lexicon_matches + service_matches],
        }
    except (ManifestError, ApplyError, OSError, ValueError) as error:
        report = {"ok": False, "error": str(error)}
    if args.json:
        print(json.dumps(report, ensure_ascii=False))
    elif "error" in report:
        print(f"FAIL: {report['error']}", file=sys.stderr)
    else:
        print(
            f"{'OK' if report['ok'] else 'FAIL'}: {report['brand']} lexicon={report['lexicon_matches']} "
            f"service_ids={report['service_identifier_matches']} self_check={report['self_check']}"
        )
        print("generation: " + json.dumps(report["generation"]))
        for match in report["matches"][:50]:
            print(f"  {match['surface']} {match['path']}:{match['line']} {match['word']!r}")
        if report["exports"]:
            print("export coverage: " + json.dumps(report["exports"]))
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
