#!/usr/bin/env python3
"""Render deployment-profile tables for every client and the backend.

One source (`deploy/profiles/*.yaml`), one resolver, five generated tables. The
point is that a client never learns *which* backend implementation it is talking
to -- it reads a profile: endpoints, identity provider, and capability switches.
That is what lets `deploy/self-host/` and `deploy/cloudflare/` be directories
rather than branches.

Generated files all live on fork-owned paths, so rendering changes no upstream
file:

    app/lib/env/fork/deployment_profiles.g.dart
    desktop/macos/Desktop/Sources/Generated/DeploymentProfiles.generated.swift
    desktop/windows/src/shared/fork/deploymentProfiles.generated.ts
    web/app/src/lib/fork/deploymentProfile.generated.ts
    backend/fork/deployment_profiles.generated.json

Usage:
    scripts/profiles/render.py --target self_hosted [--brand <id>] [--check]
    scripts/profiles/render.py --target omi_cloud --emit-json    # equivalence probe

`--manifest PATH` validates a private YAML/JSON overlay. `--stage` resolves only
that stage. `--output-root` writes an isolated build tree. Endpoint overrides
come from deployments.<target>.<stage>, without inferred auth/MCP/object URLs.

`--check` renders to memory and fails if any file on disk differs, which is how
CI proves the checked-in tables match the source.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from urllib.parse import urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "brand"))
from manifest import ManifestError, load_manifest  # noqa: E402
from yaml_lite import YamlError, load_yaml  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "backend"))
from fork.model_contract import validate_llm, validate_speech, validate as validate_embedding_contract  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
PROFILE_DIR = REPO_ROOT / "deploy/profiles"
BRAND_DIR = REPO_ROOT / "brand"

GENERATED_HEADER = "generated by scripts/profiles/render.py -- do not edit"

# Capability keys every target must declare. Listing them here rather than
# taking whatever the YAML happens to contain means a target that forgets one
# fails loudly instead of silently defaulting.
REQUIRED_CAPABILITIES = (
    "allow_direct_model_providers",
    "allow_byok",
    "allow_google_connectors",
    "allow_cloud_connectors",
    "marketplace_enabled",
    "model_downloads",
    "account_activation_fence",
    "embedding_dims",
    "sync_upload_batch_limit",
    "max_request_bytes",
    "push_provider",
    "tts_provider",
    "realtime_relay",
    "stt_providers",
)
REQUIRED_DATA_PLANE = ("store", "object_store", "queue", "vector", "cache")
STAGES = ("production", "beta", "local")


class ProfileError(RuntimeError):
    pass


ENDPOINT_KEYS = {
    "api": "api_base",
    "auth": "auth_base",
    "web": "web_app",
    "mcp": "mcp_base",
    "share": "share_base",
    "objects": "objects_base",
}


def stage_bindings(manifest: dict, target: str, stage: str) -> dict:
    domains = dict(manifest["domains"])
    domains.update(manifest.get("deployments", {}).get(target, {}).get(stage, {}))
    return {
        **{key: str(domains.get(field, "")).rstrip("/") for key, field in ENDPOINT_KEYS.items()},
        "scheme": manifest["identifiers"]["url_scheme"],
    }


def validate_endpoint(value: str, field: str, target: str, stage: str, requires_https: bool) -> None:
    parsed = urlsplit(value)
    if (
        not value
        or not parsed.hostname
        or parsed.username
        or parsed.password
        or parsed.fragment
        or parsed.query
        or parsed.scheme not in (("https",) if requires_https else ("http", "https"))
    ):
        raise ProfileError(
            f"{target}.{stage}: {field} must be an explicit {'https' if requires_https else 'http(s)'} URL without credentials/query/fragment"
        )
    try:
        parsed.port
    except ValueError as error:
        raise ProfileError(f"{target}.{stage}: invalid {field} port") from error


def substitute(value, brand: dict, target: str, stage: str):
    if not isinstance(value, str) or "{" not in value:
        return value
    out = value
    for key, replacement in brand.items():
        if "{" + key + "}" in out and not replacement:
            raise ProfileError(f"{target}.{stage}: missing explicit endpoint {ENDPOINT_KEYS.get(key, key)}")
        out = out.replace("{" + key + "}", replacement)
    if "{" in out:
        missing = out[out.index("{") + 1 : out.index("}")] if "}" in out else out
        raise ProfileError(
            f"{target}.{stage}: '{value}' needs brand key '{missing}'. "
            f"Pass --brand <id> with brand/<id>/manifest.yaml defining domains."
        )
    return out


def resolve(
    target: str, brand_id: str | None = None, manifest_path: Path | None = None, stage: str | None = None
) -> dict:
    if target not in ("omi_cloud", "self_hosted", "cloudflare") or (stage is not None and stage not in STAGES):
        raise ProfileError("unknown deployment target or stage")
    try:
        target_doc = load_yaml(PROFILE_DIR / f"{target}.yaml")
        stage_doc = load_yaml(PROFILE_DIR / "stages.yaml")
        manifest = load_manifest(brand_id, REPO_ROOT, manifest_path)
    except (ManifestError, YamlError) as error:
        raise ProfileError(str(error)) from error
    brand_id = manifest["brand"]["id"]
    selected_stages = (stage,) if stage else STAGES

    if target_doc.get("target") != target:
        raise ProfileError(f"{target}.yaml declares target '{target_doc.get('target')}'")

    caps = target_doc.get("capabilities", {}) or {}
    embedding = None
    speech = None
    llm = None
    if target == "self_hosted":
        try:
            embedding = validate_embedding_contract(target_doc.get("embedding")).as_dict()
            speech = validate_speech(target_doc.get("speech"))
            llm = validate_llm(target_doc.get("llm"))
        except ValueError as error:
            raise ProfileError(str(error)) from error
        if "embedding_dims" in caps:
            raise ProfileError("self_hosted embedding_dims must derive from the model contract")
        if "stt_providers" in caps or "tts_provider" in caps:
            raise ProfileError("self_hosted STT/TTS capabilities must derive from the speech contract")
        if "llm_provider" in caps:
            raise ProfileError("self_hosted LLM capability must derive from the model contract")
        caps = {**caps, "embedding_dims": embedding["dimension"],
                "stt_providers": ["sensevoice"] if speech else [],
                "tts_provider": "kokoro" if speech else "disabled"}
    missing = [k for k in REQUIRED_CAPABILITIES if k not in caps]
    if missing:
        raise ProfileError(f"{target}.yaml is missing capabilities: {', '.join(missing)}")
    plane = target_doc.get("data_plane", {}) or {}
    missing = [k for k in REQUIRED_DATA_PLANE if k not in plane]
    if missing:
        raise ProfileError(f"{target}.yaml is missing data_plane keys: {', '.join(missing)}")

    identity = target_doc.get("identity_provider")
    # The pairing is derived, never independently settable: an operator-run
    # deployment cannot authenticate against upstream's Firebase project.
    expected = "firebase" if target == "omi_cloud" else "better_auth"
    if identity != expected:
        raise ProfileError(f"{target}: identity_provider must be '{expected}', got '{identity}'")

    entries: dict[str, dict] = {}
    for stage in selected_stages:
        brand = stage_bindings(manifest, target, stage)
        stage_values = target_doc.get("stages", {}).get(stage)
        if stage_values is None:
            raise ProfileError(f"{target}.yaml has no stage '{stage}'")
        stage_policy = stage_doc.get("stages", {}).get(stage, {})
        row = {
            "name": f"{target}.{stage}",
            "target": target,
            "stage": stage,
            "identity_provider": identity,
            "managed": bool(target_doc.get("managed", False)),
            "allows_production_data": bool(stage_policy.get("allows_production_data", False)),
            "requires_https": bool(stage_policy.get("requires_https", False)),
            "allows_env_url_override": bool(stage_policy.get("allows_env_url_override", False)),
        }
        overrides = manifest.get("deployments", {}).get(target, {}).get(stage, {})
        output_fields = {
            "api_base_url": "api_base",
            "auth_base_url": "auth_base",
            "web_base_url": "web_app",
            "mcp_base_url": "mcp_base",
            "share_base_url": "share_base",
            "objects_base_url": "objects_base",
        }
        for key, value in stage_values.items():
            row[key] = (
                overrides[output_fields[key]]
                if output_fields.get(key) in overrides
                else substitute(value, brand, target, stage)
            )
        row["capabilities"] = {k: substitute(caps[k], brand, target, stage) for k in REQUIRED_CAPABILITIES}
        if target == "self_hosted":
            row["capabilities"]["llm_provider"] = llm.provider if llm else "disabled"
        row["data_plane"] = {k: plane[k] for k in REQUIRED_DATA_PLANE}
        if embedding is not None:
            row["embedding"] = dict(embedding)
        if speech is not None:
            row["speech"] = speech.as_dict()
        if llm is not None:
            row["llm"] = llm.as_dict()
        for key, value in row.items():
            if key.endswith("_base_url") and (target != "omi_cloud" or value):
                validate_endpoint(value, key, target, stage, row["requires_https"])
        entries[row["name"]] = row

    for alias, values in (target_doc.get("legacy_aliases", {}) if len(selected_stages) == len(STAGES) else {}).items():
        row = {
            "name": alias,
            "target": target,
            "stage": "legacy",
            "identity_provider": identity,
            "managed": bool(target_doc.get("managed", False)),
            "requires_https": False,
            "allows_env_url_override": True,
            "legacy": True,
        }
        row.update(values)
        row["capabilities"] = dict(entries[f"{target}.production"]["capabilities"])
        row["data_plane"] = dict(entries[f"{target}.production"]["data_plane"])
        entries[alias] = row

    return {"schema_version": 1, "target": target, "brand": brand_id, "profiles": entries}


def dart_literal(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(dart_literal(v) for v in value) + "]"
    if value is None:
        return "null"
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_dart(resolved: dict) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        f"// target: {resolved['target']}  brand: {resolved['brand']}",
        "//",
        "// The client reads a profile; it never learns which backend implementation",
        "// serves it. Endpoints, identity provider and capability switches all come",
        "// from here, so one binary can face self-hosted or Cloudflare.",
        "",
        "class ForkDeploymentProfile {",
        "  const ForkDeploymentProfile({",
        "    required this.name,",
        "    required this.target,",
        "    required this.stage,",
        "    required this.identityProvider,",
        "    required this.managed,",
        "    required this.apiBaseUrl,",
        "    required this.authCallbackScheme,",
        "    required this.allowsProductionData,",
        "    required this.requiresHttps,",
        "    required this.capabilities,",
        "  });",
        "",
        "  final String name;",
        "  final String target;",
        "  final String stage;",
        "  final String identityProvider;",
        "  final bool managed;",
        "  final String apiBaseUrl;",
        "  final String authCallbackScheme;",
        "  final bool allowsProductionData;",
        "  final bool requiresHttps;",
        "  final Map<String, Object?> capabilities;",
        "}",
        "",
        "const Map<String, ForkDeploymentProfile> forkDeploymentProfiles = {",
    ]
    for name, row in resolved["profiles"].items():
        caps = ", ".join(f"'{k}': {dart_literal(v)}" for k, v in row["capabilities"].items())
        lines += [
            f"  {dart_literal(name)}: ForkDeploymentProfile(",
            f"    name: {dart_literal(name)},",
            f"    target: {dart_literal(row['target'])},",
            f"    stage: {dart_literal(row['stage'])},",
            f"    identityProvider: {dart_literal(row['identity_provider'])},",
            f"    managed: {dart_literal(row['managed'])},",
            f"    apiBaseUrl: {dart_literal(row.get('api_base_url', ''))},",
            f"    authCallbackScheme: {dart_literal(row.get('auth_callback_scheme', ''))},",
            f"    allowsProductionData: {dart_literal(row.get('allows_production_data', False))},",
            f"    requiresHttps: {dart_literal(row.get('requires_https', False))},",
            f"    capabilities: {{{caps}}},",
            "  ),",
        ]
    lines += ["};", ""]
    return "\n".join(lines)


def render_swift(resolved: dict) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        f"// target: {resolved['target']}  brand: {resolved['brand']}",
        "",
        "import Foundation",
        "",
        "struct ForkDeploymentProfile: Sendable {",
        "  let name: String",
        "  let target: String",
        "  let stage: String",
        "  let identityProvider: String",
        "  let managed: Bool",
        "  let apiBaseURL: String",
        "  let authCallbackScheme: String",
        "  let allowsProductionData: Bool",
        "  let requiresHTTPS: Bool",
        "}",
        "",
        "enum ForkDeploymentProfiles {",
        "  static let all: [String: ForkDeploymentProfile] = [",
    ]
    for name, row in resolved["profiles"].items():
        lines.append(
            f'    "{name}": ForkDeploymentProfile(name: "{name}", target: "{row["target"]}", '
            f'stage: "{row["stage"]}", identityProvider: "{row["identity_provider"]}", '
            f'managed: {"true" if row["managed"] else "false"}, '
            f'apiBaseURL: "{row.get("api_base_url", "")}", '
            f'authCallbackScheme: "{row.get("auth_callback_scheme", "")}", '
            f'allowsProductionData: {"true" if row.get("allows_production_data") else "false"}, '
            f'requiresHTTPS: {"true" if row.get("requires_https") else "false"}),'
        )
    lines += ["  ]", "}", ""]
    return "\n".join(lines)


def render_ts(resolved: dict) -> str:
    body = json.dumps(resolved["profiles"], indent=2, sort_keys=True, ensure_ascii=False)
    return "\n".join(
        [
            f"// {GENERATED_HEADER}",
            f"// target: {resolved['target']}  brand: {resolved['brand']}",
            "",
            "// The type is derived from the table rather than hand-written: a field",
            "// added to deploy/profiles/ must not require editing a mirror here, and",
            "// tsc caught exactly that drift the first time this file was generated.",
            f"export const forkDeploymentProfiles = {body} as const",
            "",
            "export type ForkProfileName = keyof typeof forkDeploymentProfiles",
            "export type ForkDeploymentProfile = (typeof forkDeploymentProfiles)[ForkProfileName]",
            "",
        ]
    )


def render_backend_json(resolved: dict) -> str:
    return (
        json.dumps(
            {"_comment": GENERATED_HEADER, **resolved},
            indent=2,
            sort_keys=True,
            ensure_ascii=False,
        )
        + "\n"
    )


OUTPUTS = {
    "app/lib/env/fork/deployment_profiles.g.dart": render_dart,
    "desktop/macos/Desktop/Sources/Generated/DeploymentProfiles.generated.swift": render_swift,
    "desktop/windows/src/shared/fork/deploymentProfiles.generated.ts": render_ts,
    "web/app/src/lib/fork/deploymentProfile.generated.ts": render_ts,
    "backend/fork/deployment_profiles.generated.json": render_backend_json,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--target", required=True, choices=["omi_cloud", "self_hosted", "cloudflare"])
    parser.add_argument("--brand")
    parser.add_argument("--manifest", type=Path, help="explicit validated brand manifest (YAML or JSON)")
    parser.add_argument("--stage", choices=STAGES, help="resolve one stage; default resolves all stages")
    parser.add_argument("--output-root", type=Path, default=REPO_ROOT, help="isolated build tree for generated files")
    parser.add_argument("--check", action="store_true", help="fail if generated files differ from source")
    parser.add_argument("--emit-json", action="store_true", help="print the resolved table and write nothing")
    args = parser.parse_args()

    try:
        resolved = resolve(args.target, args.brand, args.manifest, args.stage)
    except ProfileError as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1

    if args.emit_json:
        print(json.dumps(resolved, indent=2, sort_keys=True, ensure_ascii=False))
        return 0

    drift: list[str] = []
    for rel, renderer in OUTPUTS.items():
        content = renderer(resolved)
        path = args.output_root / rel
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drift.append(rel)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    if args.check:
        if drift:
            print("FAIL: generated profile tables are stale:", file=sys.stderr)
            for rel in drift:
                print(f"  {rel}", file=sys.stderr)
            print(
                f"\nRegenerate: scripts/profiles/render.py --target {args.target} --brand {args.brand}", file=sys.stderr
            )
            return 1
        print(f"OK: {len(OUTPUTS)} generated table(s) match deploy/profiles/ for {args.target}.")
        return 0

    print(f"Rendered {len(OUTPUTS)} table(s) for target={args.target} brand={args.brand}:")
    for rel in OUTPUTS:
        print(f"  {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
