#!/usr/bin/env python3
"""Render deployment-profile tables for every client and the backend.

One source (`deploy/profiles/*.yaml`), one resolver, four generated tables. The
point is that a client never learns *which* backend implementation it is talking
to -- it reads a profile: endpoints, identity provider, and capability switches.
That is what lets `deploy/self-host/` and `deploy/cloudflare/` be directories
rather than branches.

Generated files all live on fork-owned paths, so rendering changes no upstream
file:

    app/lib/env/fork/deployment_profiles.g.dart
    desktop/macos/Desktop/Sources/Generated/DeploymentProfiles.generated.swift
    desktop/windows/src/shared/fork/deploymentProfiles.generated.ts
    web/app/src/lib/fork/deploymentProfile.generated.ts
    backend/fork/deployment_profiles.generated.json

Usage:
    scripts/profiles/render.py --target self_hosted [--brand <id>] [--check]
    scripts/profiles/render.py --target omi_cloud --emit-json    # equivalence probe

`--check` renders to memory and fails if any file on disk differs, which is how
CI proves the checked-in tables match the source.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PROFILE_DIR = REPO_ROOT / "deploy/profiles"
BRAND_DIR = REPO_ROOT / "brand"

GENERATED_HEADER = "generated by scripts/profiles/render.py -- do not edit"

# Capability keys every target must declare. Listing them here rather than
# taking whatever the YAML happens to contain means a target that forgets one
# fails loudly instead of silently defaulting.
REQUIRED_CAPABILITIES = (
    "allow_direct_model_providers",
    "allow_byok",
    "allow_google_connectors",
    "allow_cloud_connectors",
    "marketplace_enabled",
    "model_downloads",
    "account_activation_fence",
    "embedding_dims",
    "sync_upload_batch_limit",
    "max_request_bytes",
    "push_provider",
    "tts_provider",
    "realtime_relay",
    "stt_providers",
)
REQUIRED_DATA_PLANE = ("store", "object_store", "queue", "vector", "cache")
STAGES = ("production", "beta", "local")


class ProfileError(RuntimeError):
    pass


# --------------------------------------------------------------------------
# A deliberately small YAML reader.
#
# The repository's own check runner parses its manifest with a hand-rolled
# subset for the same reason: these files must be readable by a bare Python with
# no install step, on any machine, before any environment is provisioned.
# Supported: nested mappings by indentation, inline [a, b] lists, block "- "
# lists, and int/bool/null scalars.
# --------------------------------------------------------------------------
def _strip_inline_comment(text: str) -> str:
    """Drop a trailing ` # comment`, leaving quoted values intact."""
    text = text.strip()
    if text[:1] in ("\"", "'"):
        closing = text.find(text[0], 1)
        if closing != -1:
            return text[: closing + 1]
        return text
    cut = text.find(" #")
    return text[:cut].rstrip() if cut != -1 else text


def _scalar(text: str):
    text = _strip_inline_comment(text)
    if not text:
        return ""
    if text[0] in "\"'" and text[-1] == text[0] and len(text) >= 2:
        return text[1:-1]
    if text.startswith("[") and text.endswith("]"):
        inner = text[1:-1].strip()
        return [_scalar(p) for p in inner.split(",")] if inner else []
    low = text.lower()
    if low in ("true", "false"):
        return low == "true"
    if low in ("null", "~", "none"):
        return None
    try:
        return int(text)
    except ValueError:
        return text


def load_yaml(path: Path) -> dict:
    if not path.exists():
        raise ProfileError(f"missing profile source: {path}")
    root: dict = {}
    # stack of (indent, container) so nesting follows indentation
    stack: list[tuple[int, dict]] = [(-1, root)]
    pending_list: list | None = None
    pending_indent = -1

    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip())
        line = raw.strip()

        if line.startswith("- "):
            if pending_list is None or indent <= pending_indent:
                raise ProfileError(f"{path}:{lineno}: list item outside a list key")
            pending_list.append(_scalar(line[2:]))
            continue

        pending_list = None
        if ":" not in line:
            raise ProfileError(f"{path}:{lineno}: expected 'key: value'")
        key, _, value = line.partition(":")
        key, value = key.strip(), value.strip()

        while stack and indent <= stack[-1][0]:
            stack.pop()
        if not stack:
            raise ProfileError(f"{path}:{lineno}: broken indentation")
        parent = stack[-1][1]

        if value == "":
            child: dict = {}
            parent[key] = child
            stack.append((indent, child))
            pending_list = None
        elif value == "[]":
            parent[key] = []
        else:
            parsed = _scalar(value)
            parent[key] = parsed
            if parsed == "" or parsed is None:
                # "key:" followed by block list items
                parent[key] = []
                pending_list = parent[key]
                pending_indent = indent
    return root


def load_brand(brand_id: str) -> dict:
    """Domains and scheme for URL templating.

    Absent brand directory is not an error: only `self_hosted`/`cloudflare`
    templates reference it, and S1 renders `omi_cloud` (which has none) as its
    equivalence probe before any brand exists.
    """
    manifest = BRAND_DIR / brand_id / "manifest.yaml"
    if not manifest.exists():
        return {}
    data = load_yaml(manifest)
    domains = data.get("domains", {}) or {}
    identifiers = data.get("identifiers", {}) or {}
    return {
        "api": str(domains.get("api_base", "")).rstrip("/"),
        "auth": str(domains.get("auth_base", domains.get("api_base", ""))).rstrip("/"),
        "web": str(domains.get("web_app", "")).rstrip("/"),
        "mcp": str(domains.get("mcp_base", domains.get("api_base", ""))).rstrip("/"),
        "share": str(domains.get("share_base", "")).rstrip("/"),
        "objects": str(domains.get("objects_base", "")).rstrip("/"),
        "scheme": str(identifiers.get("url_scheme", brand_id)),
    }


def substitute(value, brand: dict, target: str, stage: str):
    if not isinstance(value, str) or "{" not in value:
        return value
    out = value
    for key, replacement in brand.items():
        out = out.replace("{" + key + "}", replacement)
    if "{" in out:
        missing = out[out.index("{") + 1 : out.index("}")] if "}" in out else out
        raise ProfileError(
            f"{target}.{stage}: '{value}' needs brand key '{missing}'. "
            f"Pass --brand <id> with brand/<id>/manifest.yaml defining domains."
        )
    return out


def resolve(target: str, brand_id: str) -> dict:
    target_doc = load_yaml(PROFILE_DIR / f"{target}.yaml")
    stage_doc = load_yaml(PROFILE_DIR / "stages.yaml")
    brand = load_brand(brand_id)

    if target_doc.get("target") != target:
        raise ProfileError(f"{target}.yaml declares target '{target_doc.get('target')}'")

    caps = target_doc.get("capabilities", {}) or {}
    missing = [k for k in REQUIRED_CAPABILITIES if k not in caps]
    if missing:
        raise ProfileError(f"{target}.yaml is missing capabilities: {', '.join(missing)}")
    plane = target_doc.get("data_plane", {}) or {}
    missing = [k for k in REQUIRED_DATA_PLANE if k not in plane]
    if missing:
        raise ProfileError(f"{target}.yaml is missing data_plane keys: {', '.join(missing)}")

    identity = target_doc.get("identity_provider")
    # The pairing is derived, never independently settable: an operator-run
    # deployment cannot authenticate against upstream's Firebase project.
    expected = "firebase" if target == "omi_cloud" else "better_auth"
    if identity != expected:
        raise ProfileError(f"{target}: identity_provider must be '{expected}', got '{identity}'")

    entries: dict[str, dict] = {}
    for stage in STAGES:
        stage_values = target_doc.get("stages", {}).get(stage)
        if stage_values is None:
            raise ProfileError(f"{target}.yaml has no stage '{stage}'")
        stage_policy = stage_doc.get("stages", {}).get(stage, {})
        row = {
            "name": f"{target}.{stage}",
            "target": target,
            "stage": stage,
            "identity_provider": identity,
            "managed": bool(target_doc.get("managed", False)),
            "allows_production_data": bool(stage_policy.get("allows_production_data", False)),
            "requires_https": bool(stage_policy.get("requires_https", False)),
            "allows_env_url_override": bool(stage_policy.get("allows_env_url_override", False)),
        }
        for key, value in stage_values.items():
            row[key] = substitute(value, brand, target, stage)
        row["capabilities"] = {k: substitute(caps[k], brand, target, stage) for k in REQUIRED_CAPABILITIES}
        row["data_plane"] = {k: plane[k] for k in REQUIRED_DATA_PLANE}
        if row["requires_https"]:
            for key, value in row.items():
                if key.endswith("_base_url") and isinstance(value, str) and value and not value.startswith("https://"):
                    raise ProfileError(f"{target}.{stage}: {key} must be https, got '{value}'")
        entries[row["name"]] = row

    for alias, values in (target_doc.get("legacy_aliases", {}) or {}).items():
        row = {"name": alias, "target": target, "stage": "legacy", "identity_provider": identity,
               "managed": bool(target_doc.get("managed", False)), "requires_https": False,
               "allows_env_url_override": True, "legacy": True}
        row.update(values)
        row["capabilities"] = dict(entries[f"{target}.production"]["capabilities"])
        row["data_plane"] = dict(entries[f"{target}.production"]["data_plane"])
        entries[alias] = row

    return {"schema_version": 1, "target": target, "brand": brand_id, "profiles": entries}


def dart_literal(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(dart_literal(v) for v in value) + "]"
    if value is None:
        return "null"
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_dart(resolved: dict) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        f"// target: {resolved['target']}  brand: {resolved['brand']}",
        "//",
        "// The client reads a profile; it never learns which backend implementation",
        "// serves it. Endpoints, identity provider and capability switches all come",
        "// from here, so one binary can face self-hosted or Cloudflare.",
        "",
        "class ForkDeploymentProfile {",
        "  const ForkDeploymentProfile({",
        "    required this.name,",
        "    required this.target,",
        "    required this.stage,",
        "    required this.identityProvider,",
        "    required this.managed,",
        "    required this.apiBaseUrl,",
        "    required this.authCallbackScheme,",
        "    required this.allowsProductionData,",
        "    required this.requiresHttps,",
        "    required this.capabilities,",
        "  });",
        "",
        "  final String name;",
        "  final String target;",
        "  final String stage;",
        "  final String identityProvider;",
        "  final bool managed;",
        "  final String apiBaseUrl;",
        "  final String authCallbackScheme;",
        "  final bool allowsProductionData;",
        "  final bool requiresHttps;",
        "  final Map<String, Object?> capabilities;",
        "}",
        "",
        "const Map<String, ForkDeploymentProfile> forkDeploymentProfiles = {",
    ]
    for name, row in resolved["profiles"].items():
        caps = ", ".join(f"'{k}': {dart_literal(v)}" for k, v in row["capabilities"].items())
        lines += [
            f"  {dart_literal(name)}: ForkDeploymentProfile(",
            f"    name: {dart_literal(name)},",
            f"    target: {dart_literal(row['target'])},",
            f"    stage: {dart_literal(row['stage'])},",
            f"    identityProvider: {dart_literal(row['identity_provider'])},",
            f"    managed: {dart_literal(row['managed'])},",
            f"    apiBaseUrl: {dart_literal(row.get('api_base_url', ''))},",
            f"    authCallbackScheme: {dart_literal(row.get('auth_callback_scheme', ''))},",
            f"    allowsProductionData: {dart_literal(row.get('allows_production_data', False))},",
            f"    requiresHttps: {dart_literal(row.get('requires_https', False))},",
            f"    capabilities: {{{caps}}},",
            "  ),",
        ]
    lines += ["};", ""]
    return "\n".join(lines)


def render_swift(resolved: dict) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        f"// target: {resolved['target']}  brand: {resolved['brand']}",
        "",
        "import Foundation",
        "",
        "struct ForkDeploymentProfile: Sendable {",
        "  let name: String",
        "  let target: String",
        "  let stage: String",
        "  let identityProvider: String",
        "  let managed: Bool",
        "  let apiBaseURL: String",
        "  let authCallbackScheme: String",
        "  let allowsProductionData: Bool",
        "  let requiresHTTPS: Bool",
        "}",
        "",
        "enum ForkDeploymentProfiles {",
        "  static let all: [String: ForkDeploymentProfile] = [",
    ]
    for name, row in resolved["profiles"].items():
        lines.append(
            f'    "{name}": ForkDeploymentProfile(name: "{name}", target: "{row["target"]}", '
            f'stage: "{row["stage"]}", identityProvider: "{row["identity_provider"]}", '
            f'managed: {"true" if row["managed"] else "false"}, '
            f'apiBaseURL: "{row.get("api_base_url", "")}", '
            f'authCallbackScheme: "{row.get("auth_callback_scheme", "")}", '
            f'allowsProductionData: {"true" if row.get("allows_production_data") else "false"}, '
            f'requiresHTTPS: {"true" if row.get("requires_https") else "false"}),'
        )
    lines += ["  ]", "}", ""]
    return "\n".join(lines)


def render_ts(resolved: dict) -> str:
    body = json.dumps(resolved["profiles"], indent=2, sort_keys=True, ensure_ascii=False)
    return "\n".join([
        f"// {GENERATED_HEADER}",
        f"// target: {resolved['target']}  brand: {resolved['brand']}",
        "",
        "// The type is derived from the table rather than hand-written: a field",
        "// added to deploy/profiles/ must not require editing a mirror here, and",
        "// tsc caught exactly that drift the first time this file was generated.",
        f"export const forkDeploymentProfiles = {body} as const",
        "",
        "export type ForkProfileName = keyof typeof forkDeploymentProfiles",
        "export type ForkDeploymentProfile = (typeof forkDeploymentProfiles)[ForkProfileName]",
        "",
    ])


def render_backend_json(resolved: dict) -> str:
    return json.dumps(
        {"_comment": GENERATED_HEADER, **resolved},
        indent=2, sort_keys=True, ensure_ascii=False,
    ) + "\n"


OUTPUTS = {
    "app/lib/env/fork/deployment_profiles.g.dart": render_dart,
    "desktop/macos/Desktop/Sources/Generated/DeploymentProfiles.generated.swift": render_swift,
    "desktop/windows/src/shared/fork/deploymentProfiles.generated.ts": render_ts,
    "web/app/src/lib/fork/deploymentProfile.generated.ts": render_ts,
    "backend/fork/deployment_profiles.generated.json": render_backend_json,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--target", required=True, choices=["omi_cloud", "self_hosted", "cloudflare"])
    parser.add_argument("--brand", default="omi-upstream")
    parser.add_argument("--check", action="store_true", help="fail if generated files differ from source")
    parser.add_argument("--emit-json", action="store_true", help="print the resolved table and write nothing")
    args = parser.parse_args()

    try:
        resolved = resolve(args.target, args.brand)
    except ProfileError as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1

    if args.emit_json:
        print(json.dumps(resolved, indent=2, sort_keys=True, ensure_ascii=False))
        return 0

    drift: list[str] = []
    for rel, renderer in OUTPUTS.items():
        content = renderer(resolved)
        path = REPO_ROOT / rel
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drift.append(rel)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    if args.check:
        if drift:
            print("FAIL: generated profile tables are stale:", file=sys.stderr)
            for rel in drift:
                print(f"  {rel}", file=sys.stderr)
            print(f"\nRegenerate: scripts/profiles/render.py --target {args.target} --brand {args.brand}", file=sys.stderr)
            return 1
        print(f"OK: {len(OUTPUTS)} generated table(s) match deploy/profiles/ for {args.target}.")
        return 0

    print(f"Rendered {len(OUTPUTS)} table(s) for target={args.target} brand={args.brand}:")
    for rel in OUTPUTS:
        print(f"  {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
