# generated by scripts/brand/apply.py -- do not edit
# Source of truth: brand/omi-upstream/manifest.yaml identifiers.macos_named_bundle_prefix
OMI_NAMED_BUNDLE_ID_PREFIX="com.omi."
OMI_NAMED_BUNDLE_SLUG_PREFIX="omi"
