-- Reviewed historical chat-file promotion markers.
--
-- The 0119 ledger is generated by an offline planner and is never sufficient
-- to make a file readable.  These rows bind an operator-reviewed plan to the
-- canonical file, the account generation and the external provider
-- attestation.  R2 bytes and provider objects are still checked by the Jobs
-- executor immediately before the canonical row is committed.
ALTER TABLE cf_chat_file_import_ledger
  ADD COLUMN account_generation INTEGER
  CHECK (account_generation IS NULL OR account_generation >= 0);

CREATE INDEX IF NOT EXISTS cf_chat_file_import_ledger_generation_idx
  ON cf_chat_file_import_ledger(uid, account_generation, status, updated_at DESC);

CREATE TABLE IF NOT EXISTS cf_chat_file_history_review_batches (
  review_id TEXT PRIMARY KEY CHECK (length(review_id) = 36),
  uid TEXT NOT NULL CHECK (length(uid) BETWEEN 1 AND 256),
  manifest_sha256 TEXT NOT NULL CHECK (length(manifest_sha256) = 64 AND manifest_sha256 NOT GLOB '*[^0-9a-f]*'),
  account_generation INTEGER NOT NULL CHECK (account_generation >= 0),
  entry_count INTEGER NOT NULL CHECK (entry_count > 0 AND entry_count <= 50),
  status TEXT NOT NULL CHECK (status IN ('approved', 'applied', 'revoked')),
  reviewed_at INTEGER NOT NULL CHECK (reviewed_at > 0),
  expires_at INTEGER NOT NULL CHECK (expires_at > reviewed_at),
  updated_at INTEGER NOT NULL CHECK (updated_at > 0),
  UNIQUE (uid, manifest_sha256)
);

CREATE TABLE IF NOT EXISTS cf_chat_file_history_review_items (
  review_id TEXT NOT NULL REFERENCES cf_chat_file_history_review_batches(review_id),
  uid TEXT NOT NULL CHECK (length(uid) BETWEEN 1 AND 256),
  import_id TEXT NOT NULL CHECK (length(import_id) = 64 AND import_id NOT GLOB '*[^0-9a-f]*'),
  file_id TEXT NOT NULL CHECK (length(file_id) BETWEEN 1 AND 128),
  source_file_id TEXT NOT NULL CHECK (length(source_file_id) BETWEEN 1 AND 128),
  source_object_uri TEXT NOT NULL CHECK (length(source_object_uri) BETWEEN 1 AND 1024),
  source_generation TEXT CHECK (source_generation IS NULL OR length(source_generation) BETWEEN 1 AND 256),
  checksum_sha256 TEXT NOT NULL CHECK (length(checksum_sha256) = 64 AND checksum_sha256 NOT GLOB '*[^0-9a-f]*'),
  provider_file_id TEXT NOT NULL CHECK (length(provider_file_id) BETWEEN 1 AND 256),
  name TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 512),
  mime_type TEXT NOT NULL CHECK (length(mime_type) BETWEEN 1 AND 200),
  size INTEGER NOT NULL CHECK (size > 0 AND size <= 52428800),
  storage_key TEXT NOT NULL CHECK (length(storage_key) BETWEEN 1 AND 512),
  request_fingerprint TEXT NOT NULL CHECK (length(request_fingerprint) = 64 AND request_fingerprint NOT GLOB '*[^0-9a-f]*'),
  plan_hash TEXT NOT NULL CHECK (length(plan_hash) = 64 AND plan_hash NOT GLOB '*[^0-9a-f]*'),
  account_generation INTEGER NOT NULL CHECK (account_generation >= 0),
  created_at INTEGER NOT NULL CHECK (created_at > 0),
  updated_at INTEGER NOT NULL CHECK (updated_at > 0),
  PRIMARY KEY (review_id, uid, import_id),
  UNIQUE (review_id, uid, file_id),
  UNIQUE (review_id, provider_file_id)
);

CREATE INDEX IF NOT EXISTS cf_chat_file_history_review_items_lookup_idx
  ON cf_chat_file_history_review_items(uid, import_id, plan_hash, account_generation);

CREATE TABLE IF NOT EXISTS cf_chat_file_history_applies (
  uid TEXT NOT NULL CHECK (length(uid) BETWEEN 1 AND 256),
  import_id TEXT NOT NULL CHECK (length(import_id) = 64 AND import_id NOT GLOB '*[^0-9a-f]*'),
  review_id TEXT NOT NULL REFERENCES cf_chat_file_history_review_batches(review_id),
  file_id TEXT NOT NULL CHECK (length(file_id) BETWEEN 1 AND 128),
  provider_file_id TEXT NOT NULL CHECK (length(provider_file_id) BETWEEN 1 AND 256),
  checksum_sha256 TEXT NOT NULL CHECK (length(checksum_sha256) = 64 AND checksum_sha256 NOT GLOB '*[^0-9a-f]*'),
  plan_hash TEXT NOT NULL CHECK (length(plan_hash) = 64 AND plan_hash NOT GLOB '*[^0-9a-f]*'),
  account_generation INTEGER NOT NULL CHECK (account_generation >= 0),
  status TEXT NOT NULL CHECK (status = 'applied'),
  applied_at INTEGER NOT NULL CHECK (applied_at > 0),
  updated_at INTEGER NOT NULL CHECK (updated_at > 0),
  PRIMARY KEY (uid, import_id),
  UNIQUE (uid, file_id),
  UNIQUE (provider_file_id)
);

CREATE INDEX IF NOT EXISTS cf_chat_file_history_applies_review_idx
  ON cf_chat_file_history_applies(review_id, status, updated_at DESC);

CREATE TRIGGER IF NOT EXISTS adf_i_chat_file_history_review_batches
BEFORE INSERT ON cf_chat_file_history_review_batches
WHEN EXISTS (SELECT 1 FROM cf_account_deletion_intents WHERE uid = NEW.uid)
   OR EXISTS (SELECT 1 FROM cf_account_deletion_tombstones WHERE uid = NEW.uid)
BEGIN SELECT RAISE(ABORT, 'account deletion fence'); END;

CREATE TRIGGER IF NOT EXISTS adf_u_chat_file_history_review_batches
BEFORE UPDATE ON cf_chat_file_history_review_batches
WHEN EXISTS (SELECT 1 FROM cf_account_deletion_intents WHERE uid IN (OLD.uid, NEW.uid))
   OR EXISTS (SELECT 1 FROM cf_account_deletion_tombstones WHERE uid IN (OLD.uid, NEW.uid))
BEGIN SELECT RAISE(ABORT, 'account deletion fence'); END;

CREATE TRIGGER IF NOT EXISTS adf_i_chat_file_history_review_items
BEFORE INSERT ON cf_chat_file_history_review_items
WHEN EXISTS (SELECT 1 FROM cf_account_deletion_intents WHERE uid = NEW.uid)
   OR EXISTS (SELECT 1 FROM cf_account_deletion_tombstones WHERE uid = NEW.uid)
BEGIN SELECT RAISE(ABORT, 'account deletion fence'); END;

CREATE TRIGGER IF NOT EXISTS adf_u_chat_file_history_review_items
BEFORE UPDATE ON cf_chat_file_history_review_items
WHEN EXISTS (SELECT 1 FROM cf_account_deletion_intents WHERE uid IN (OLD.uid, NEW.uid))
   OR EXISTS (SELECT 1 FROM cf_account_deletion_tombstones WHERE uid IN (OLD.uid, NEW.uid))
BEGIN SELECT RAISE(ABORT, 'account deletion fence'); END;

-- A receipt cannot be written unless the review, ledger and ready canonical
-- row agree.  R2 HEAD and provider HMAC checks are deliberately kept in Jobs.
CREATE TRIGGER IF NOT EXISTS validate_chat_file_history_apply
BEFORE INSERT ON cf_chat_file_history_applies
WHEN EXISTS (SELECT 1 FROM cf_account_deletion_intents WHERE uid = NEW.uid)
   OR EXISTS (SELECT 1 FROM cf_account_deletion_tombstones WHERE uid = NEW.uid)
   OR NOT EXISTS (
     SELECT 1 FROM cf_account_cutover AS c
     WHERE c.uid = NEW.uid AND c.state = 'new'
       AND c.checkpoint_phase = 'completed'
       AND c.destination_backend_bound = 1
       AND c.account_generation = NEW.account_generation
   )
   OR NOT EXISTS (
     SELECT 1 FROM cf_chat_file_history_review_items AS i
     WHERE i.review_id = NEW.review_id AND i.uid = NEW.uid
       AND i.import_id = NEW.import_id AND i.file_id = NEW.file_id
       AND i.provider_file_id = NEW.provider_file_id
       AND i.checksum_sha256 = NEW.checksum_sha256
       AND i.plan_hash = NEW.plan_hash
       AND i.account_generation = NEW.account_generation
   )
   OR NOT EXISTS (
     SELECT 1 FROM cf_chat_file_import_ledger AS l
     WHERE l.uid = NEW.uid AND l.import_id = NEW.import_id
       AND l.plan_hash = NEW.plan_hash AND l.status = 'applied'
       AND l.account_generation = NEW.account_generation
   )
   OR NOT EXISTS (
     SELECT 1 FROM cf_chat_files AS f
     WHERE f.uid = NEW.uid AND f.file_id = NEW.file_id
       AND f.provider_file_id = NEW.provider_file_id
       AND f.checksum_sha256 = NEW.checksum_sha256
       AND f.status = 'ready'
   )
BEGIN SELECT RAISE(ABORT, 'chat file history authority changed'); END;

CREATE TRIGGER IF NOT EXISTS adf_u_chat_file_history_applies
BEFORE UPDATE ON cf_chat_file_history_applies
WHEN EXISTS (SELECT 1 FROM cf_account_deletion_intents WHERE uid IN (OLD.uid, NEW.uid))
   OR EXISTS (SELECT 1 FROM cf_account_deletion_tombstones WHERE uid IN (OLD.uid, NEW.uid))
BEGIN SELECT RAISE(ABORT, 'account deletion fence'); END;
