// generated by scripts/profiles/render.py -- do not edit
// target: omi_cloud  brand: omi-upstream
//
// The client reads a profile; it never learns which backend implementation
// serves it. Endpoints, identity provider and capability switches all come
// from here, so one binary can face self-hosted or Cloudflare.

class ForkDeploymentProfile {
  const ForkDeploymentProfile({
    required this.name,
    required this.target,
    required this.stage,
    required this.identityProvider,
    required this.managed,
    required this.apiBaseUrl,
    required this.authCallbackScheme,
    required this.allowsProductionData,
    required this.requiresHttps,
    required this.capabilities,
  });

  final String name;
  final String target;
  final String stage;
  final String identityProvider;
  final bool managed;
  final String apiBaseUrl;
  final String authCallbackScheme;
  final bool allowsProductionData;
  final bool requiresHttps;
  final Map<String, Object?> capabilities;
}

const Map<String, ForkDeploymentProfile> forkDeploymentProfiles = {
  'omi_cloud.production': ForkDeploymentProfile(
    name: 'omi_cloud.production',
    target: 'omi_cloud',
    stage: 'production',
    identityProvider: 'firebase',
    managed: true,
    apiBaseUrl: 'https://api.omi.me/',
    authCallbackScheme: 'omi',
    allowsProductionData: true,
    requiresHttps: true,
    capabilities: {'allow_direct_model_providers': true, 'allow_byok': true, 'allow_google_connectors': true, 'allow_cloud_connectors': true, 'marketplace_enabled': true, 'model_downloads': true, 'account_activation_fence': false, 'embedding_dims': 3072, 'sync_upload_batch_limit': 5, 'max_request_bytes': 0, 'push_provider': 'firebase', 'tts_provider': 'elevenlabs', 'realtime_relay': 'openai', 'stt_providers': []},
  ),
  'omi_cloud.beta': ForkDeploymentProfile(
    name: 'omi_cloud.beta',
    target: 'omi_cloud',
    stage: 'beta',
    identityProvider: 'firebase',
    managed: true,
    apiBaseUrl: 'https://api.omiapi.com/',
    authCallbackScheme: 'omi-beta',
    allowsProductionData: true,
    requiresHttps: true,
    capabilities: {'allow_direct_model_providers': true, 'allow_byok': true, 'allow_google_connectors': true, 'allow_cloud_connectors': true, 'marketplace_enabled': true, 'model_downloads': true, 'account_activation_fence': false, 'embedding_dims': 3072, 'sync_upload_batch_limit': 5, 'max_request_bytes': 0, 'push_provider': 'firebase', 'tts_provider': 'elevenlabs', 'realtime_relay': 'openai', 'stt_providers': []},
  ),
  'omi_cloud.local': ForkDeploymentProfile(
    name: 'omi_cloud.local',
    target: 'omi_cloud',
    stage: 'local',
    identityProvider: 'firebase',
    managed: true,
    apiBaseUrl: 'http://127.0.0.1:8000/',
    authCallbackScheme: 'omi-dev',
    allowsProductionData: false,
    requiresHttps: false,
    capabilities: {'allow_direct_model_providers': true, 'allow_byok': true, 'allow_google_connectors': true, 'allow_cloud_connectors': true, 'marketplace_enabled': true, 'model_downloads': true, 'account_activation_fence': false, 'embedding_dims': 3072, 'sync_upload_batch_limit': 5, 'max_request_bytes': 0, 'push_provider': 'firebase', 'tts_provider': 'elevenlabs', 'realtime_relay': 'openai', 'stt_providers': []},
  ),
  'local_prod': ForkDeploymentProfile(
    name: 'local_prod',
    target: 'omi_cloud',
    stage: 'legacy',
    identityProvider: 'firebase',
    managed: true,
    apiBaseUrl: 'http://127.0.0.1:8000/',
    authCallbackScheme: 'omi',
    allowsProductionData: true,
    requiresHttps: false,
    capabilities: {'allow_direct_model_providers': true, 'allow_byok': true, 'allow_google_connectors': true, 'allow_cloud_connectors': true, 'marketplace_enabled': true, 'model_downloads': true, 'account_activation_fence': false, 'embedding_dims': 3072, 'sync_upload_batch_limit': 5, 'max_request_bytes': 0, 'push_provider': 'firebase', 'tts_provider': 'elevenlabs', 'realtime_relay': 'openai', 'stt_providers': []},
  ),
};
