// generated by scripts/profiles/render.py -- do not edit
// target: self_hosted  brand: eddy
//
// The client reads a profile; it never learns which backend implementation
// serves it. Endpoints, identity provider and capability switches all come
// from here, so one binary can face self-hosted or Cloudflare.

class ForkDeploymentProfile {
  const ForkDeploymentProfile({
    required this.name,
    required this.target,
    required this.stage,
    required this.identityProvider,
    required this.managed,
    required this.apiBaseUrl,
    required this.authCallbackScheme,
    required this.allowsProductionData,
    required this.requiresHttps,
    required this.capabilities,
  });

  final String name;
  final String target;
  final String stage;
  final String identityProvider;
  final bool managed;
  final String apiBaseUrl;
  final String authCallbackScheme;
  final bool allowsProductionData;
  final bool requiresHttps;
  final Map<String, Object?> capabilities;
}

const Map<String, ForkDeploymentProfile> forkDeploymentProfiles = {
  'self_hosted.local': ForkDeploymentProfile(
    name: 'self_hosted.local',
    target: 'self_hosted',
    stage: 'local',
    identityProvider: 'better_auth',
    managed: false,
    apiBaseUrl: 'http://127.0.0.1:8100/',
    authCallbackScheme: 'eddy-dev',
    allowsProductionData: false,
    requiresHttps: false,
    capabilities: {'allow_direct_model_providers': false, 'allow_byok': false, 'allow_google_connectors': false, 'allow_cloud_connectors': false, 'marketplace_enabled': false, 'model_downloads': false, 'account_activation_fence': false, 'embedding_dims': 1024, 'sync_upload_batch_limit': 5, 'max_request_bytes': 0, 'push_provider': 'disabled', 'tts_provider': 'openrouter', 'realtime_relay': 'operator', 'stt_providers': ['openrouter'], 'llm_provider': 'openrouter'},
  ),
};
