// generated by scripts/profiles/render.py -- do not edit
// target: self_hosted  brand: eddy

// The type is derived from the table rather than hand-written: a field
// added to deploy/profiles/ must not require editing a mirror here, and
// tsc caught exactly that drift the first time this file was generated.
export const forkDeploymentProfiles = {
  "self_hosted.local": {
    "allows_env_url_override": true,
    "allows_production_data": false,
    "api_base_url": "http://127.0.0.1:8100/",
    "auth_base_url": "http://127.0.0.1:3000",
    "auth_callback_scheme": "eddy-dev",
    "capabilities": {
      "account_activation_fence": false,
      "allow_byok": false,
      "allow_cloud_connectors": false,
      "allow_direct_model_providers": false,
      "allow_google_connectors": false,
      "embedding_dims": 1024,
      "llm_provider": "openrouter",
      "marketplace_enabled": false,
      "max_request_bytes": 0,
      "model_downloads": false,
      "push_provider": "disabled",
      "realtime_relay": "operator",
      "stt_providers": [
        "openrouter"
      ],
      "sync_upload_batch_limit": 5,
      "tts_provider": "openrouter"
    },
    "data_plane": {
      "cache": "redis",
      "object_store": "minio",
      "queue": "redis",
      "store": "firestore_pg",
      "vector": "pgvector"
    },
    "identity_provider": "better_auth",
    "managed": false,
    "mcp_base_url": "http://127.0.0.1:8100",
    "name": "self_hosted.local",
    "objects_base_url": "http://127.0.0.1:9000",
    "operator_ai": {
      "account_id": "",
      "asr_base_url": "https://openrouter.ai/api/v1",
      "asr_model": "openai/whisper-large-v3",
      "base_url": "https://openrouter.ai/api/v1",
      "embedding_base_url": "https://openrouter.ai/api/v1",
      "embedding_dimension": 1024,
      "embedding_model": "baai/bge-m3",
      "gateway_id": "",
      "max_output_tokens": 8192,
      "model": "qwen/qwen3-8b",
      "provider": "openrouter",
      "request_timeout_seconds": 120,
      "tts_base_url": "https://openrouter.ai/api/v1",
      "tts_model": "minimax/speech-2.8-turbo",
      "tts_response_format": "mp3",
      "tts_voice": "female-shaonv"
    },
    "requires_https": false,
    "share_base_url": "http://127.0.0.1:3001",
    "stage": "local",
    "target": "self_hosted",
    "web_base_url": "http://127.0.0.1:3001"
  }
} as const

export type ForkProfileName = keyof typeof forkDeploymentProfiles
export type ForkDeploymentProfile = (typeof forkDeploymentProfiles)[ForkProfileName]
