"""Brand-owned firmware release policy for the Server OS target.

The upstream firmware router remains intact. At Server OS admission its narrow
lookup seams are patched to this module, which reads the generated policy baked
into the image and fetches only the operator's explicit manifest transport.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable
from urllib.parse import urlsplit

from utils.http_client import get_web_fetch_client

from .registry import Patch

CONFIG_PATH = Path(__file__).with_name("firmware_brand.generated.json")
_POLICY_KEYS = {
    "schema_version",
    "brand_id",
    "device_model",
    "device_model_aliases",
    "release_tag_prefix",
    "release_asset_prefix",
    "github_releases_url",
}
_PREFIX = re.compile(r"^[A-Za-z0-9_]+_v$")
_BRAND_ID = re.compile(r"^[a-z0-9][a-z0-9-]*$")
_VERSION = r"[0-9]+(?:\.[0-9]+){1,2}"


class FirmwarePolicyError(RuntimeError):
    pass


@dataclass(frozen=True)
class FirmwarePolicy:
    brand_id: str
    device_model: str
    device_model_aliases: tuple[str, ...]
    release_tag_prefix: str
    release_asset_prefix: str

    @property
    def tag_pattern(self) -> re.Pattern[str]:
        return re.compile(rf"^{re.escape(self.release_tag_prefix)}{_VERSION}$", re.IGNORECASE)

    @property
    def release_prefix(self) -> str:
        return self.release_tag_prefix.removesuffix("_v")

    def supports_model(self, model: object) -> bool:
        return isinstance(model, str) and (model == self.device_model or model in self.device_model_aliases)


@dataclass(frozen=True)
class FirmwareDevice:
    """A CV1 device marker that remains distinct from upstream enum members."""

    policy: FirmwarePolicy


def _plain(value: object, label: str) -> str:
    if not isinstance(value, str) or not value.strip() or any(ord(char) < 32 or ord(char) == 127 for char in value):
        raise FirmwarePolicyError(f"{label} must be a non-empty plain string")
    return value


def _exact(value: object, keys: set[str], label: str) -> dict[str, Any]:
    if not isinstance(value, dict) or set(value) != keys:
        raise FirmwarePolicyError(f"{label} must contain exactly: {', '.join(sorted(keys))}")
    return value


def load_policy(path: Path | None = None) -> FirmwarePolicy:
    path = path or CONFIG_PATH
    try:
        raw = path.read_text(encoding="utf-8")
        if raw.startswith("// generated by scripts/brand/apply.py -- do not edit\n"):
            raw = raw.split("\n", 1)[1]
        config = json.loads(raw)
    except (OSError, ValueError) as error:
        raise FirmwarePolicyError(f"cannot load generated firmware policy: {error}") from error
    config = _exact(config, {"schema_version", "brand_id", "build", "release"}, "firmware config")
    if config["schema_version"] != 1 or not _BRAND_ID.fullmatch(_plain(config["brand_id"], "brand_id")):
        raise FirmwarePolicyError("unsupported firmware config identity")
    release = _exact(config["release"], _POLICY_KEYS, "firmware release policy")
    if release["schema_version"] != 1 or release["brand_id"] != config["brand_id"]:
        raise FirmwarePolicyError("firmware release policy belongs to another brand")
    device_model = _plain(release["device_model"], "device_model")
    aliases = release["device_model_aliases"]
    if not isinstance(aliases, list) or not aliases or len(aliases) > 8:
        raise FirmwarePolicyError("firmware aliases are invalid")
    aliases = tuple(_plain(value, "device_model_aliases") for value in aliases)
    if device_model in aliases or len(aliases) != len(set(aliases)):
        raise FirmwarePolicyError("firmware aliases must be distinct")
    tag_prefix = _plain(release["release_tag_prefix"], "release_tag_prefix")
    asset_prefix = _plain(release["release_asset_prefix"], "release_asset_prefix")
    if not _PREFIX.fullmatch(tag_prefix) or asset_prefix != tag_prefix[:-1] + "OTA_v":
        raise FirmwarePolicyError("firmware release naming policy is invalid")
    release_url = _plain(release["github_releases_url"], "github_releases_url")
    parsed = urlsplit(release_url)
    if (
        parsed.scheme != "https"
        or not parsed.hostname
        or parsed.username
        or parsed.password
        or parsed.query
        or parsed.fragment
    ):
        raise FirmwarePolicyError("firmware release source must be an explicit HTTPS URL")
    return FirmwarePolicy(config["brand_id"], device_model, aliases, tag_prefix, asset_prefix)


def _operator_manifest_url() -> str:
    if os.getenv("FIRMWARE_RELEASE_TRANSPORT", "").strip() != "manifest":
        raise FirmwarePolicyError("self-hosted firmware requires manifest transport")
    value = os.getenv("FIRMWARE_RELEASE_MANIFEST_URL", "").strip()
    parsed = urlsplit(value)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname or parsed.username or parsed.password:
        raise FirmwarePolicyError("FIRMWARE_RELEASE_MANIFEST_URL must be an explicit HTTP(S) URL")
    return value


async def operator_manifest_releases(
    policy: FirmwarePolicy,
    tag_filter: re.Pattern[str] | None,
    *,
    client_factory: Callable[[], Any] | None = None,
) -> list[dict[str, Any]]:
    """Fetch the configured operator manifest without a GitHub fallback."""

    url = _operator_manifest_url()
    if client_factory is None:
        client_factory = get_web_fetch_client
    headers = {"accept": "application/json"}
    bearer = os.getenv("FIRMWARE_RELEASE_MANIFEST_BEARER_TOKEN", "").strip()
    if bearer:
        headers["authorization"] = f"Bearer {bearer}"
    try:
        response = await client_factory().get(url, headers=headers)
        if response.status_code != 200:
            return []
        payload = response.json()
    except Exception:
        return []
    if not isinstance(payload, list):
        return []
    pattern = tag_filter or policy.tag_pattern
    return [
        release
        for release in payload
        if isinstance(release, dict)
        and isinstance(release.get("tag_name"), str)
        and pattern.fullmatch(release["tag_name"])
    ]


def _self_hosted(row: dict) -> bool:
    return row.get("target") == "self_hosted"


def _policy_pattern(_original: Any) -> re.Pattern[str]:
    return load_policy().tag_pattern


def _device_lookup(_original: Any) -> Callable[[str], FirmwareDevice | None]:
    policy = load_policy()

    def lookup(device_model: str) -> FirmwareDevice | None:
        return FirmwareDevice(policy) if policy.supports_model(device_model) else None

    return lookup


def _release_prefix(_original: Any) -> Callable[[FirmwareDevice], str]:
    def prefix(device: FirmwareDevice) -> str:
        if not isinstance(device, FirmwareDevice):
            raise FirmwarePolicyError("firmware router received an unowned device identity")
        return device.policy.release_prefix

    return prefix


def _manifest_releases(_original: Any) -> Callable[..., Any]:
    policy = load_policy()

    async def releases(_cache_key: str, tag_filter: re.Pattern[str] | None = None):
        return await operator_manifest_releases(policy, tag_filter or policy.tag_pattern)

    return releases


def patches() -> list[Patch]:
    return [
        Patch(
            name="firmware.policy.tag-pattern",
            module="routers.firmware",
            attribute="FIRMWARE_TAG_PATTERN",
            build=_policy_pattern,
            applies_to=_self_hosted,
            reason="a Server OS firmware route accepts only the image brand's CV1 release tags",
        ),
        Patch(
            name="firmware.policy.device-model",
            module="routers.firmware",
            attribute="_get_device_by_model_number",
            build=_device_lookup,
            applies_to=_self_hosted,
            reason="firmware model admission belongs to the selected brand policy, never upstream aliases",
        ),
        Patch(
            name="firmware.policy.release-prefix",
            module="routers.firmware",
            attribute="_get_release_prefix",
            build=_release_prefix,
            applies_to=_self_hosted,
            reason="the operator manifest must use the same CV1 release prefix the staged firmware receives",
        ),
        Patch(
            name="firmware.operator-manifest",
            module="routers.firmware",
            attribute="get_omi_github_releases",
            build=_manifest_releases,
            applies_to=_self_hosted,
            reason="Server OS firmware discovery reads the configured operator manifest and never falls back to GitHub",
        ),
    ]
