// generated by scripts/profiles/render.py -- do not edit
// target: omi_cloud  brand: omi-upstream

// The type is derived from the table rather than hand-written: a field
// added to deploy/profiles/ must not require editing a mirror here, and
// tsc caught exactly that drift the first time this file was generated.
export const forkDeploymentProfiles = {
  "local_prod": {
    "allows_env_url_override": true,
    "allows_production_data": true,
    "api_base_url": "http://127.0.0.1:8000/",
    "auth_callback_scheme": "omi",
    "capabilities": {
      "account_activation_fence": false,
      "allow_byok": true,
      "allow_cloud_connectors": true,
      "allow_direct_model_providers": true,
      "allow_google_connectors": true,
      "embedding_dims": 3072,
      "marketplace_enabled": true,
      "max_request_bytes": 0,
      "model_downloads": true,
      "push_provider": "firebase",
      "realtime_relay": "openai",
      "stt_providers": [],
      "sync_upload_batch_limit": 5,
      "tts_provider": "elevenlabs"
    },
    "data_plane": {
      "cache": "redis",
      "object_store": "gcs",
      "queue": "cloud_tasks",
      "store": "firestore",
      "vector": "pinecone"
    },
    "firebase_project_id": "based-hardware",
    "identity_provider": "firebase",
    "legacy": true,
    "managed": true,
    "name": "local_prod",
    "requires_https": false,
    "stage": "legacy",
    "target": "omi_cloud",
    "uses_firebase_auth_emulator": false
  },
  "omi_cloud.beta": {
    "allows_env_url_override": false,
    "allows_production_data": true,
    "api_base_url": "https://api.omiapi.com/",
    "auth_api_base_url": "https://api.omi.me/",
    "auth_callback_scheme": "omi-beta",
    "capabilities": {
      "account_activation_fence": false,
      "allow_byok": true,
      "allow_cloud_connectors": true,
      "allow_direct_model_providers": true,
      "allow_google_connectors": true,
      "embedding_dims": 3072,
      "marketplace_enabled": true,
      "max_request_bytes": 0,
      "model_downloads": true,
      "push_provider": "firebase",
      "realtime_relay": "openai",
      "stt_providers": [],
      "sync_upload_batch_limit": 5,
      "tts_provider": "elevenlabs"
    },
    "data_plane": {
      "cache": "redis",
      "object_store": "gcs",
      "queue": "cloud_tasks",
      "store": "firestore",
      "vector": "pinecone"
    },
    "firebase_project_id": "based-hardware",
    "identity_provider": "firebase",
    "managed": true,
    "name": "omi_cloud.beta",
    "requires_https": true,
    "stage": "beta",
    "target": "omi_cloud",
    "uses_firebase_auth_emulator": false
  },
  "omi_cloud.local": {
    "allows_env_url_override": true,
    "allows_production_data": false,
    "api_base_url": "http://127.0.0.1:8000/",
    "auth_callback_scheme": "omi-dev",
    "capabilities": {
      "account_activation_fence": false,
      "allow_byok": true,
      "allow_cloud_connectors": true,
      "allow_direct_model_providers": true,
      "allow_google_connectors": true,
      "embedding_dims": 3072,
      "marketplace_enabled": true,
      "max_request_bytes": 0,
      "model_downloads": true,
      "push_provider": "firebase",
      "realtime_relay": "openai",
      "stt_providers": [],
      "sync_upload_batch_limit": 5,
      "tts_provider": "elevenlabs"
    },
    "data_plane": {
      "cache": "redis",
      "object_store": "gcs",
      "queue": "cloud_tasks",
      "store": "firestore",
      "vector": "pinecone"
    },
    "firebase_project_id": "demo-omi-local",
    "identity_provider": "firebase",
    "managed": true,
    "name": "omi_cloud.local",
    "requires_https": false,
    "stage": "local",
    "target": "omi_cloud",
    "uses_firebase_auth_emulator": true
  },
  "omi_cloud.production": {
    "allows_env_url_override": false,
    "allows_production_data": true,
    "api_base_url": "https://api.omi.me/",
    "auth_callback_scheme": "omi",
    "capabilities": {
      "account_activation_fence": false,
      "allow_byok": true,
      "allow_cloud_connectors": true,
      "allow_direct_model_providers": true,
      "allow_google_connectors": true,
      "embedding_dims": 3072,
      "marketplace_enabled": true,
      "max_request_bytes": 0,
      "model_downloads": true,
      "push_provider": "firebase",
      "realtime_relay": "openai",
      "stt_providers": [],
      "sync_upload_batch_limit": 5,
      "tts_provider": "elevenlabs"
    },
    "data_plane": {
      "cache": "redis",
      "object_store": "gcs",
      "queue": "cloud_tasks",
      "store": "firestore",
      "vector": "pinecone"
    },
    "firebase_project_id": "based-hardware",
    "identity_provider": "firebase",
    "managed": true,
    "name": "omi_cloud.production",
    "requires_https": true,
    "stage": "production",
    "target": "omi_cloud",
    "uses_firebase_auth_emulator": false
  }
} as const

export type ForkProfileName = keyof typeof forkDeploymentProfiles
export type ForkDeploymentProfile = (typeof forkDeploymentProfiles)[ForkProfileName]
