#!/usr/bin/env python3
"""Stage a CV1 firmware tree from a generated brand identity input.

This command is intentionally a staging step, not a release command.  It
never resolves a signing-key reference and never invokes a publisher.  Build
the resulting ``firmware`` directory with the normal NCS/MCUboot pipeline only
after a release operator supplies the referenced signing key.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CONFIG = ROOT / "backend/fork/firmware_brand.generated.json"
SOURCE = ROOT / "omi/firmware/omi"
NFC_PATH = Path("src/lib/core/nfc.c")


class StageError(RuntimeError):
    pass


def _exact_keys(value: object, expected: set[str], label: str) -> dict:
    if not isinstance(value, dict) or set(value) != expected:
        raise StageError(f"{label} must contain exactly: {', '.join(sorted(expected))}")
    return value


def load_config(path: Path) -> dict:
    try:
        raw = path.read_text(encoding="utf-8")
        if raw.startswith("// generated by scripts/brand/apply.py -- do not edit\n"):
            raw = raw.split("\n", 1)[1]
        config = json.loads(raw)
    except (OSError, ValueError) as error:
        raise StageError(f"cannot load generated firmware config {path}: {error}") from error
    _exact_keys(config, {"schema_version", "brand_id", "build", "release"}, "firmware config")
    if config["schema_version"] != 1 or not isinstance(config["brand_id"], str):
        raise StageError("unsupported firmware config identity")
    build = _exact_keys(
        config["build"],
        {
            "ble_name",
            "ble_name_devkit",
            "dis_manufacturer",
            "dis_model_cv1",
            "nfc_pair_url",
            "service_uuid_base",
            "mcuboot_signing_key",
        },
        "firmware build identity",
    )
    release = _exact_keys(
        config["release"],
        {
            "schema_version",
            "brand_id",
            "device_model",
            "device_model_aliases",
            "release_tag_prefix",
            "release_asset_prefix",
            "github_releases_url",
        },
        "firmware release policy",
    )
    if release["schema_version"] != 1 or release["brand_id"] != config["brand_id"]:
        raise StageError("firmware release policy belongs to another brand")
    if build["dis_model_cv1"] != release["device_model"]:
        raise StageError("firmware build model and release model differ")
    if not isinstance(build["nfc_pair_url"], str) or build["nfc_pair_url"].count("%s") != 1:
        raise StageError("firmware NFC pairing URL needs exactly one device-id placeholder")
    if len(build["nfc_pair_url"].replace("%s", "ABC123")) >= 64:
        raise StageError("firmware NFC pairing URL exceeds the CV1 URI buffer")
    for name in ("ble_name", "dis_manufacturer", "dis_model_cv1"):
        value = build[name]
        if not isinstance(value, str) or not value or any(ord(char) < 32 or char in '\\\"' for char in value):
            raise StageError(f"firmware build identity {name} is unsafe")
    return config


def _replace_kconfig(text: str, name: str, value: str) -> str:
    pattern = re.compile(rf"^{re.escape(name)}=.*$", re.MULTILINE)
    replacement = f'{name}="{value}"'
    text, changed = pattern.subn(replacement, text)
    if changed != 1:
        raise StageError(f"expected exactly one {name} assignment in staged omi.conf")
    return text


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def stage(config: dict, output: Path) -> dict[str, object]:
    if output.exists() or output.is_symlink():
        raise StageError(f"staging output already exists: {output}")
    if not SOURCE.is_dir():
        raise StageError(f"upstream firmware source is missing: {SOURCE}")
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.parent.is_symlink():
        raise StageError("staging output parent cannot be a symlink")
    temp = Path(tempfile.mkdtemp(prefix=f".{output.name}.stage-", dir=output.parent))
    try:
        staged = temp / "firmware"
        shutil.copytree(SOURCE, staged)
        build = config["build"]
        conf_path = staged / "omi.conf"
        conf = conf_path.read_text(encoding="utf-8")
        for key, value in (
            ("CONFIG_BT_DEVICE_NAME", build["ble_name"]),
            ("CONFIG_BT_DIS_MODEL", build["dis_model_cv1"]),
            ("CONFIG_BT_DIS_MANUF", build["dis_manufacturer"]),
        ):
            conf = _replace_kconfig(conf, key, value)
        conf_path.write_text(conf, encoding="utf-8")

        nfc_path = staged / NFC_PATH
        nfc = nfc_path.read_text(encoding="utf-8")
        source_url = '"https://friend.based.com/pair?id=%s"'
        target_url = json.dumps(build["nfc_pair_url"])
        changed = nfc.count(source_url)
        nfc = nfc.replace(source_url, target_url)
        if changed != 1:
            raise StageError("expected one upstream NFC pairing URL in staged source")
        nfc_path.write_text(nfc, encoding="utf-8")

        release = config["release"]
        public_release = {key: release[key] for key in sorted(release)}
        (temp / "firmware-release-policy.json").write_text(
            json.dumps(public_release, indent=2) + "\n", encoding="utf-8"
        )
        metadata = {
            "schema_version": 1,
            "brand_id": config["brand_id"],
            "source": "omi/firmware/omi staged without modifying the checkout",
            "firmware": {
                "omi_conf_sha256": _digest(conf_path),
                "nfc_source_sha256": _digest(nfc_path),
            },
            "release_policy": public_release,
            "signing": {
                "key_reference": build["mcuboot_signing_key"],
                "key_resolved": False,
                "release_qualified": False,
            },
        }
        (temp / "stage.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
        os.replace(temp, output)
        return metadata
    except BaseException:
        shutil.rmtree(temp, ignore_errors=True)
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        metadata = stage(load_config(args.config), args.output)
    except StageError as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1
    print(json.dumps(metadata, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
