"""The `desktop` category generator (B1, first slice: `app-config.sh`'s prefix).

`desktop/macos/scripts/app-config.sh` hard-rejects any named test bundle
whose slug does not start with `omi-` (`derive_omi_app_config` in that file).
That is upstream's own dev-loop tooling, not fork-owned, so the fork cannot
just edit its logic freely -- the T1 seam in
dev/unified-main/upstream-touch-allowlist.yaml budgets exactly 3 added lines
there, meaning this generator's job is to produce a value app-config.sh
*sources*, not to reimplement the script.

Only this one file is registered under `desktop` today. AppBuild.swift,
Info.plist templating, create-omi-beta-variant.sh, BundleEnvironment.swift,
and backend/database/desktop_previews.py are the rest of the B1 row in
dev/unified-main/07-pr-plan.md and are NOT covered here -- BundleEnvironment.swift
specifically overlaps with S3's own planned rewrite of the same file
("统一配置模块"), so building brand-injection logic on top of it now risks
being redone. Tracked in dev/unified-main/08-m2-cloudflare-followups.md-style
notes; see this generator's own limitations in the B1 PR description.
"""

from __future__ import annotations

from pathlib import Path

GENERATED_HEADER = "# generated by scripts/brand/apply.py -- do not edit"

APP_CONFIG_BRAND_PATH = "desktop/macos/scripts/app-config.brand.sh"


def _named_bundle_slug_prefix(reverse_domain_prefix: str) -> str:
    """Derive the plain slug prefix ("omi") from the reverse-domain one ("com.omi.").

    The slug prefix is what a named bundle's OMI_APP_NAME is checked against
    (`omi-<feature>`); the reverse-domain prefix is what its bundle id is
    built from (`com.omi.<slug>`). Both come from one manifest field so a
    brand only states its identity once.
    """
    segments = [s for s in reverse_domain_prefix.split(".") if s]
    if not segments:
        raise ValueError(f"macos_named_bundle_prefix {reverse_domain_prefix!r} has no segments")
    return segments[-1]


def render(brand_id: str, manifest: dict, repo_root: Path) -> list[Path]:
    prefix = manifest["identifiers"]["macos_named_bundle_prefix"]
    slug_prefix = _named_bundle_slug_prefix(prefix)

    content = (
        f"{GENERATED_HEADER}\n"
        f"# Source of truth: brand/{brand_id}/manifest.yaml identifiers.macos_named_bundle_prefix\n"
        f'OMI_NAMED_BUNDLE_ID_PREFIX="{prefix}"\n'
        f'OMI_NAMED_BUNDLE_SLUG_PREFIX="{slug_prefix}"\n'
    )

    target = repo_root / APP_CONFIG_BRAND_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return [target]
