"""Render the fork-owned firmware identity and OTA policy input.

The upstream firmware source is deliberately left byte-identical.  The
``omi/firmware/fork/stage.py`` consumer copies that source into an isolated
build directory and applies this generated input there.  Server OS and
Cloudflare consume the smaller public release policy from the same document.
"""

from __future__ import annotations

import json
import re
from urllib.parse import urlsplit

GENERATED_HEADER = "generated by scripts/brand/apply.py -- do not edit"
FIRMWARE_CONFIG_PATH = "backend/fork/firmware_brand.generated.json"
MODEL_ALIASES = ("nrf5340",)
_SAFE_KCONFIG_VALUE = re.compile(r"^[^\x00-\x1f\x7f\\\"]+$")
_REPOSITORY = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")


class FirmwareRenderError(ValueError):
    """A schema-valid manifest cannot safely configure the CV1 build."""


def _safe_kconfig_value(name: str, value: object) -> str:
    if not isinstance(value, str) or not value or not _SAFE_KCONFIG_VALUE.fullmatch(value):
        raise FirmwareRenderError(f"device.{name} must be a non-empty Kconfig-safe string")
    return value


def _release_policy(manifest: dict) -> dict[str, object]:
    device = manifest["device"]
    prefix = device["firmware_release_prefix"]
    if not isinstance(prefix, str) or not re.fullmatch(r"[A-Za-z0-9_]+_v", prefix):
        raise FirmwareRenderError("device.firmware_release_prefix must end in '_v'")
    repository = manifest["distribution"]["github_releases_repo"]
    if not isinstance(repository, str) or not _REPOSITORY.fullmatch(repository):
        raise FirmwareRenderError("distribution.github_releases_repo must be an owner/repository pair")
    return {
        "schema_version": 1,
        "brand_id": manifest["brand"]["id"],
        "device_model": _safe_kconfig_value("dis_model_cv1", device["dis_model_cv1"]),
        "device_model_aliases": list(MODEL_ALIASES),
        "release_tag_prefix": prefix,
        "release_asset_prefix": prefix[:-1] + "OTA_v",
        "github_releases_url": f"https://api.github.com/repos/{repository}/releases",
    }


def public_policy(manifest: dict) -> dict[str, object]:
    """Return only the safe OTA lookup policy projected to public runtimes."""

    return _release_policy(manifest)


def generated_config(manifest: dict) -> dict[str, object]:
    """Return the complete, non-secret staging input for one firmware brand."""

    device = manifest["device"]
    nfc_pair_url = device["nfc_pair_url"]
    if not isinstance(nfc_pair_url, str) or nfc_pair_url.count("%s") != 1:
        raise FirmwareRenderError("device.nfc_pair_url must contain exactly one '%s' device-id placeholder")
    parsed = urlsplit(nfc_pair_url)
    if parsed.scheme != "https" or not parsed.hostname or parsed.username or parsed.password or parsed.fragment:
        raise FirmwareRenderError("device.nfc_pair_url must be an explicit HTTPS URL without credentials or fragments")
    # The CV1 source uses a 64-byte URI buffer including the NUL terminator,
    # and its hardware identifier currently contributes six characters.
    if len(nfc_pair_url.replace("%s", "ABC123")) >= 64:
        raise FirmwareRenderError("device.nfc_pair_url exceeds the CV1 NFC URI buffer")
    return {
        "schema_version": 1,
        "brand_id": manifest["brand"]["id"],
        "build": {
            "ble_name": _safe_kconfig_value("ble_name", device["ble_name"]),
            "ble_name_devkit": _safe_kconfig_value("ble_name_devkit", device["ble_name_devkit"]),
            "dis_manufacturer": _safe_kconfig_value("dis_manufacturer", device["dis_manufacturer"]),
            "dis_model_cv1": _safe_kconfig_value("dis_model_cv1", device["dis_model_cv1"]),
            "nfc_pair_url": nfc_pair_url,
            "service_uuid_base": device["service_uuid_base"],
            "mcuboot_signing_key": device["mcuboot_signing_key"],
        },
        "release": _release_policy(manifest),
    }


def render(manifest: dict) -> dict[str, str]:
    config = generated_config(manifest)
    return {
        FIRMWARE_CONFIG_PATH: "// " + GENERATED_HEADER + "\n" + json.dumps(config, indent=2, sort_keys=True) + "\n",
    }
