"""Shared firmware manifest validator.

Single source of truth for every regex / structural check that the fork's
firmware pipeline applies to a generated brand firmware config. Both the
producer (``scripts/brand/generators/firmware.py``) and the consumer
(``omi/firmware/fork/stage.py``) call this module so a relaxed check on one
side cannot drift from a strict check on the other.

The backend ``backend/fork/firmware.py::load_policy`` validator is
**deliberately kept independent** of this module: importing the
``scripts/brand/generators/`` tree from ``backend/`` would pull in
``sys.path`` mutations and generator-side I/O assumptions that the
backend's import-time patch contract forbids. Backend's validator is a
strict *subset* (it re-reads the same generated JSON and enforces only the
fields it consumes) and is exercised by ``backend/fork/tests/test_firmware.py``.

Consumers:

- :func:`validate_generated_config` - structural + field validation of the
  already-rendered JSON config (the post-generation contract).
- :func:`validate_brand_manifest_source` - pre-render validation of the
  brand manifest YAML (the producer-side contract).

Every check returns the validated value or raises :class:`FirmwareValidationError`.
Error messages are stable identifiers (``"nfc_pair_url: ..."``, ``"release_tag_prefix: ..."``)
so the existing test assertions that match message substrings stay green.
"""

from __future__ import annotations

import re
from typing import Any
from urllib.parse import urlsplit

# ---- Constants shared with the producer and the stage consumer. ----------------

GENERATED_HEADER = "generated by scripts/brand/apply.py -- do not edit"
SCHEMA_VERSION = 1
MODEL_ALIASES: tuple[str, ...] = ("nrf5340",)

# Top-level exact keys required on a generated firmware config.
TOP_KEYS: frozenset[str] = frozenset({"schema_version", "brand_id", "build", "release"})
BUILD_KEYS: frozenset[str] = frozenset(
    {
        "ble_name",
        "ble_name_devkit",
        "dis_manufacturer",
        "dis_model_cv1",
        "nfc_pair_url",
        "service_uuid_base",
        "mcuboot_signing_key",
    }
)
RELEASE_KEYS: frozenset[str] = frozenset(
    {
        "schema_version",
        "brand_id",
        "device_model",
        "device_model_aliases",
        "release_tag_prefix",
        "release_asset_prefix",
        "github_releases_url",
    }
)

# Regexes (kept module-level so they compile once and are easy to audit).
_SAFE_KCONFIG_VALUE = re.compile(r"^[^\x00-\x1f\x7f\\\"]+$")
_RELEASE_TAG_PREFIX = re.compile(r"^[A-Za-z0-9_]+_v$")
_RELEASE_ASSET_SUFFIX = "OTA_v"
_GITHUB_REPOSITORY = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
# NFC URI buffer in the CV1 firmware source (64 bytes including NUL terminator).
# A device-id placeholder counts as six characters in the current hardware ID.
_NFC_URI_BUFFER = 64
_NFC_PLACEHOLDER = "%s"
_NFC_PLACEHOLDER_PROBE = "ABC123"  # six chars, matches the current hw-id length.


class FirmwareValidationError(ValueError):
    """Raised when a firmware manifest / config violates a shared constraint."""


# ---- Helpers ------------------------------------------------------------------


def _require_keys(value: Any, expected: frozenset[str], label: str) -> dict[str, Any]:
    if not isinstance(value, dict) or set(value) != set(expected):
        raise FirmwareValidationError(
            f"{label} must contain exactly: {', '.join(sorted(expected))}"
        )
    return value


def _safe_kconfig_value(name: str, value: Any) -> str:
    if not isinstance(value, str) or not value or not _SAFE_KCONFIG_VALUE.fullmatch(value):
        raise FirmwareValidationError(f"device.{name} must be a non-empty Kconfig-safe string")
    return value


def _kconfig_unsafe_chars(name: str, value: Any) -> str:
    """Mirror stage.py's looser kconfig check used when ``strict`` is False.

    The stage consumer historically checked ``ble_name`` / ``dis_manufacturer`` /
    ``dis_model_cv1`` against ``ord(char) < 32 or char in '\\"'``. Kept here so
    the shared validator can run in either strict (full kconfig regex) or
    compat (control-char + backslash + quote) mode without losing either side's
    invariant.
    """
    if not isinstance(value, str) or not value or any(
        ord(char) < 32 or char in '\\"' for char in value
    ):
        raise FirmwareValidationError(f"firmware build identity {name} is unsafe")
    return value


def _validate_nfc_pair_url(value: Any) -> str:
    if not isinstance(value, str) or value.count(_NFC_PLACEHOLDER) != 1:
        raise FirmwareValidationError(
            f"device.nfc_pair_url must contain exactly one '{_NFC_PLACEHOLDER}' device-id placeholder"
        )
    parsed = urlsplit(value)
    if (
        parsed.scheme != "https"
        or not parsed.hostname
        or parsed.username
        or parsed.password
        or parsed.fragment
    ):
        raise FirmwareValidationError(
            "device.nfc_pair_url must be an explicit HTTPS URL without credentials or fragments"
        )
    if len(value.replace(_NFC_PLACEHOLDER, _NFC_PLACEHOLDER_PROBE)) >= _NFC_URI_BUFFER:
        raise FirmwareValidationError("device.nfc_pair_url exceeds the CV1 NFC URI buffer")
    return value


def _validate_release_policy(release: dict[str, Any], brand_id: str) -> None:
    if release["schema_version"] != SCHEMA_VERSION or release["brand_id"] != brand_id:
        raise FirmwareValidationError("firmware release policy belongs to another brand")
    prefix = release["release_tag_prefix"]
    if not isinstance(prefix, str) or not _RELEASE_TAG_PREFIX.fullmatch(prefix):
        raise FirmwareValidationError("device.firmware_release_prefix must end in '_v'")
    expected_asset = prefix[:-1] + _RELEASE_ASSET_SUFFIX
    if release["release_asset_prefix"] != expected_asset:
        raise FirmwareValidationError("firmware release naming policy is invalid")
    url = release["github_releases_url"]
    # The generated config exposes the resolved GitHub API URL
    # (``https://api.github.com/repos/<owner>/<repo>/releases``); enforce that
    # scheme + host + owner/repo path-segment shape here. Empty / wrong-shape
    # URLs from a broken producer should never reach the stage consumer.
    parsed = urlsplit(url)
    if (
        not isinstance(url, str)
        or parsed.scheme != "https"
        or parsed.netloc != "api.github.com"
        or not parsed.path.startswith("/repos/")
    ):
        raise FirmwareValidationError(
            "github_releases_url must be the GitHub Releases API URL for the configured repo"
        )
    owner_repo = parsed.path[len("/repos/"):].rstrip("/").removesuffix("/releases")
    if not owner_repo or not _GITHUB_REPOSITORY.fullmatch(owner_repo):
        raise FirmwareValidationError(
            "github_releases_url must reference an owner/repository pair"
        )


# ---- Public API ---------------------------------------------------------------


def validate_brand_manifest_source(manifest: dict) -> None:
    """Validate the *pre-render* brand manifest YAML.

    Mirrors the field-by-field checks the producer used to perform inline.
    Callers must invoke this *before* rendering so the generated JSON is
    guaranteed to satisfy :func:`validate_generated_config` too.
    """

    device = manifest["device"]
    if "firmware_release_prefix" not in device:
        raise FirmwareValidationError("device.firmware_release_prefix is required")
    prefix = device["firmware_release_prefix"]
    if not isinstance(prefix, str) or not _RELEASE_TAG_PREFIX.fullmatch(prefix):
        raise FirmwareValidationError("device.firmware_release_prefix must end in '_v'")
    repository = manifest["distribution"]["github_releases_repo"]
    if not isinstance(repository, str) or not _GITHUB_REPOSITORY.fullmatch(repository):
        raise FirmwareValidationError(
            "distribution.github_releases_repo must be an owner/repository pair"
        )
    _safe_kconfig_value("dis_model_cv1", device["dis_model_cv1"])
    _validate_nfc_pair_url(device["nfc_pair_url"])


def validate_generated_config(config: Any, *, strict: bool = True) -> dict[str, Any]:
    """Validate the *post-render* generated JSON config.

    When ``strict`` is True (default) the full kconfig regex is applied to
    ``ble_name`` / ``dis_manufacturer`` / ``dis_model_cv1``; this matches the
    producer's original check. When ``strict`` is False the looser
    control-char + backslash + quote check is used (the historical stage.py
    behavior), so a config produced by a future producer that loosens kconfig
    safety can still be staged without a producer-side change.
    """

    check = _safe_kconfig_value if strict else _kconfig_unsafe_chars
    config = _require_keys(config, TOP_KEYS, "firmware config")
    if config["schema_version"] != SCHEMA_VERSION or not isinstance(config["brand_id"], str):
        raise FirmwareValidationError("unsupported firmware config identity")
    brand_id = config["brand_id"]
    build = _require_keys(config["build"], BUILD_KEYS, "firmware build identity")
    release = _require_keys(config["release"], RELEASE_KEYS, "firmware release policy")
    # Run kconfig safety on build identity *before* any cross-field check so a
    # bad dis_model_cv1 surfaces as a kconfig error, not as a misleading
    # "build model and release model differ" downstream.
    for name in ("ble_name", "dis_manufacturer", "dis_model_cv1"):
        check(name, build[name])
    _validate_nfc_pair_url(build["nfc_pair_url"])
    if release["device_model"] != build["dis_model_cv1"]:
        raise FirmwareValidationError("firmware build model and release model differ")
    _validate_release_policy(release, brand_id)
    return config
