"""The `flutter` category generator (B2, first slice: the mobile app title).

`app/lib/flavors.dart`'s `F.title` getter hardcodes "Omi" / "Omi Dev" -- the
mobile app's runtime display title (`MaterialApp(title: F.title)` in
`main.dart`). That's a T1 seam
(dev/unified-main/upstream-touch-allowlist.yaml), budgeted at 3 added lines:
one import, and the two existing return statements each substituting in the
generated constant.

Only this one file is registered under `flutter` today. `app/flavorizr.yaml`
(bundle ids/icons/app names per flavor -- the actual on-home-screen app
identity, which needs `flutter_flavorizr` re-run against Xcode/Android
project files, not just a value swap), the 3 pbxproj escape points,
entitlements (App Group/associated domains), and `environment_profile.dart`'s
OAuth callback URL scheme are the rest of the B2 row in
dev/unified-main/07-pr-plan.md and are NOT covered here.

In particular, `environment_profile.dart`'s `authCallbackScheme` must land
together with the native URL-scheme registration (Info.plist
CFBundleURLSchemes / AndroidManifest.xml intent-filter) that has to match it
byte-for-byte for OAuth redirect to actually work -- doing one without the
other ships a broken, half-finished login path for any non-omi-upstream
brand, so both need to move as one unit next time, not piecemeal now.
"""

from __future__ import annotations

from pathlib import Path

GENERATED_HEADER = "// generated by scripts/brand/apply.py -- do not edit"

FLAVORS_BRAND_PATH = "app/lib/flavors.brand.dart"


def _dart_string_literal(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def render(manifest: dict, repo_root: Path) -> list[Path]:
    brand_id = manifest["brand"]["id"]
    display_name = manifest["brand"]["display_name"]

    content = (
        f"{GENERATED_HEADER}\n"
        f"// Source of truth: brand/{brand_id}/manifest.yaml brand.display_name\n"
        f"const String kBrandDisplayName = {_dart_string_literal(display_name)};\n"
    )

    target = repo_root / FLAVORS_BRAND_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return [target]
